### ISSUE TITLE
Please document supported CSS

### ISSUE THREAD

**Issue by mpkelly** [cristianbote/goober#104]
Hello, 

Great project and one which I am keeping an eye on. I tried to use Goober on a project of mine and while it worked for 90% of stuff there were some weird bugs when I started nesting rules and using pseudo selectors - sorry I didn't report them. In the end I switched over the styled-components so I could keep working but I'd like to use Goober as my project is a text editor and goober is small enough to bundle along with it. My request is that you outline what CSS is supported and what isn't or at least include any fairly common selectors that aren't supported in the readme. All I could find was "basic CSS parsing". 

Thanks
Mike

**Comment by cristianbote** [comment]
Hey @mpkelly! Thanks for opening this issue!

That's kinda strange cause nesting should be fine as long as you follow the `stylis` pseudo css code. Would definitely help an example. There's a case where nesting multiple pseudo-selectors can get weird in terms that the output it's larger than it should.

I would love to have an example, that would help a lot.

**Comment by mpkelly** [comment]
@cristianbote I figured there was some known issues/limitations that weren't documented so didn't provide an example. It was actually a month or so ago when I hit these problems and switched to SC. I'm am almost done with my side project and will try switching back to Goober in the next week or two. I will report any issues I hit and open a new ticket. Thanks!
