### ISSUE TITLE
`glob` styles to apply on SSR

### ISSUE THREAD

**Issue by inandsza** [cristianbote/goober#105]
hellooo!

Not sure if this is an issue or I need to do something to make the glob styles apply on the server

Do the 'glob' styles only get applied on the client?
Is there a way to make it apply on the server with the rest of the css?

**Comment by cristianbote** [comment]
Hey @inandsza, thanks for opening this issue!

Can you share your setup? I can give more info on it if I can play with a reproducing example.

**Comment by cristianbote** [comment]
This has been stale for a while, but now you can use the `createGlobalStyle` that will ensure that each time the global component is used, the styles are added to the cache. If that was the issue or the confusion, then this is taken care of.
