### ISSUE TITLE
0 (zero) values in tagged templates aren't being parsed

### ISSUE THREAD

**Issue by raulgg** [cristianbote/goober#108]
When a 0 (zero) is is being passed to a tagged template it isn't being parsed into the CSS output.

I've set up a simple example reproducing this small issue.

https://codesandbox.io/s/goober-template-issue-vxlmf?fontsize=14&hidenavigation=1&theme=dark

![Screen Shot 2020-02-06 at 14 37 09](https://user-images.githubusercontent.com/7021021/73984742-31044080-48ee-11ea-943b-c18f1ef5677a.png)

![Screen Shot 2020-02-06 at 14 35 34](https://user-images.githubusercontent.com/7021021/73984703-15993580-48ee-11ea-9ed7-3655dcab88c1.png)

**Comment by cristianbote** [comment]
Hey @raulgg! Thank you for opening this issue! Oh wow, having a reproducing example is soooo awesome to be able to see the issue. 👍 

Indeed, apparently inside here https://github.com/cristianbote/goober/blob/master/src/core/compile.js#L31 that line should basically check for nullish values instead.
```js
        return out + next + (tail == null ? '' : tail);
```

If you feel like it, you can open a PR with that exact fix 😄 if not I'll do it later.

**Comment by cristianbote** [comment]
Fixed in `goober@1.7.0` 🎉
