### ISSUE TITLE
Publish a github page entry as a landing page

### ISSUE THREAD

**Issue by cristianbote** [cristianbote/goober#112]
Looking over `js.org` we could get a `goober.js.org` entry if we publish a github page with a landing page for goober. That'll be awesome.

**Comment by nygdjs** [comment]
Will be awesome, definitely! (I think this is not even a question :D)
If needed, happy to help putting the page together 🙋‍♂️

**Comment by cristianbote** [comment]
Wow! Thank you! That'll be awesome! Feel free to start on it 😃 I'm open to _anything_

**Comment by nygdjs** [comment]
Sorry for the delayed answer...
Would be happy to help on this!
I have a few questions tho:
- Do goober has any kind of design, or and idea, anything you already thought about? A logo/logo idea maybe?
- I was thinking about either a Gatsby site or a very simple vanilla HTML/CSS static thing. Do you have any preference regarding this?
- Should it be just a "teaser" like landing page or something more? Maybe with examples or some documentation like stuff too?

**Comment by vandreleal** [comment]
@cristianbote, here's the PR pending approval for https://goober.js.org -> https://github.com/js-org/js.org/pull/5317

**Comment by cristianbote** [comment]
Thank you @vandreleal! 🙏
