### ISSUE TITLE
can I use it with react native/expo?

### ISSUE THREAD

**Issue by NomanGul** [cristianbote/goober#12]

**Comment by cristianbote** [comment]
Hey Noman! Thank you so much for reaching out!

Unfortunately, that would not work. The styling on react native, has a different kind of inner workings. So, I don't think this is gonna ever be working in react-native.

Also, if I'm not mistaken - it's been a while, react-native has great support for styling with stylesheets. Is there a particular reason you would like to use something else?

**Comment by NomanGul** [comment]
@cristianbote Nope... Just asking because I like goober lib :+1:

**Comment by RayyanNafees** [comment]
But `styled-components` do support react native tho... they just omit some of the functionality when working with native like `keyframes` etc but borders, shadows and even transformations work like a charm
