### ISSUE TITLE
Using Goober in component libraries

### ISSUE THREAD

**Issue by mjanssen** [cristianbote/goober#127]
Hey hey - Is there already an example how to utilise the speed and functionalities of Goober in component libraries? I know there are enough examples with Styled components and Emotion, but I have the feeling Goober is extremely good since the size of the library.

Whenever I try to build a component in a component library, I seem to be unable to get the styles in the application that imports the component (using Next.js).

**Comment by mjanssen** [comment]
So basically, the component is rendered correctly, when JS is enabled. This is caused because Goober renders the component (from the component library) and injects the styles.

If I try to extract the css using extractCss, I get an empty string returned, so without JS, the styles are not available in the Front-end.

**Comment by cristianbote** [comment]
Hey there! Thanks for opening this issue! 😄 So, just as with styled-components/emotion/etc you need to handle the whole style tag -- SSR part, within the `_app.js` and `_document.js` files. Let me put together a codesandbox to highlight the changes needed. Afterwards that codesandbox could be a great candidate for #30.

**Comment by cristianbote** [comment]
Alrighty, here you go https://codesandbox.io/s/nextjs-with-goober-ktgkw. Let me know if this works for you. ✌️

**Comment by mjanssen** [comment]
Thanks Cristian! This works in an instant :)

However; building an application using babel etc etc. where Goober is used as an CSS in JS layer, I am unable to use these components in another project.

I have created this temp branch to view what I'm actually talking about: https://github.com/domparty/component-library/blob/tmp/src/components/Image/Image.tsx

It's building (npm run build) into ./lib.

The error I'm getting when importing ie. the Image component is:

"TypeError: u is not a function", which is thrown by Goober 🤔

**Comment by cristianbote** [comment]
Oh, ok. Now I see what's going on 😃 So, the `setPragma` call is missing, meaning `goober` has no idea which jsx function -- pragma, to call. That means, you would need a way to tell the inner compiled goober instance to use `React.createElement`/`h`.

Another question how would you import the `Image` above? Based on it's path inside `lib`? I'm guessing, but you might need something at the top level to define some options/theme/colors? If yes, that'll be the best option 😀 Something like:

```jsx
import { Provider } from 'domparty';

<Provider value={{
    colors: { ... }
  }}>
  <App />
</Provider>

```

```js
import React, { createContext } from 'react';
import { setPragma } from 'goober';

// Here is the best spot to call it
setPragma(React.createElement);

const ctx = createContext({});

export const Provider = ({ value, children }) => {
  return (
    <ctx.Provider value={value>
      {children}
    </ctx.Provider>
  );
};
```

It doesn't need to be this way but most of the time this is what I found to be useful.

If you do not have a top-level provider that would mean inside each of the component, you would need to call `setPragma`.

**Comment by mjanssen** [comment]
Wew, I feel like such a noobie right now 😅

I tried calling setPragma from the main app, which obviously doesn't work... I believe the use of Context is also a great method to pass theming to components, so appreciated of thinking about this as well 😄.

**Comment by cristianbote** [comment]
Oh please don't feel like one! We're all in this together 😃 Can't count the number of _hours_ I've spent for example debugging why something doesn't work just to realise it wasn't called at all 🙈 

Yup, also for `goober@2` 😄 the context will be essential for passing down themes or other stuff.

**Comment by Remeic** [comment]
Hi @cristianbote, i'be created a little codesandbox usign nextjs with preact and goober, but there is an error:
`TypeError: i is not a function
    at Object.s (/Users/giulio/Documents/Personale/Preact/justgiulio_preact/node_modules/goober/dist/goober.js:1:2031)
    at g (/Users/giulio/Documents/Personale/Preact/justgiulio_preact/node_modules/preact-render-to-string/dist/index.js:1:2247)`
https://codesandbox.io/s/blissful-blackburn-cwiqd

**Comment by Remeic** [comment]
Thanks for quick reply @cristianbote!
Before submitting the codesandbox i've tried to set `setup(h)` in _app.js but it doesn't worked
I've tried some minutes ago to fork your codesandbox, but `SmallTitle` component seems doesn't affected by styled.
For example font-size: 13em, i've missed something else?

**Comment by cristianbote** [comment]
Ah, I just realised that you are using a `next.js` environment 🤦  so sorry. So inside `_app.js` is the place to call the `setup` method. And you are already doing it properly 👍 . So I went back to my sandbox, which is a fork of yours, and I notice that style definition had the color `"red"` in quotes inside the tagged template. That's invalid CSS I believe so I corrected that, restarted the sandbox and it works 🎉  https://codesandbox.io/s/bold-waterfall-ltzpx?file=/pages/index.js

Can you give it a go and let me know if that helps?

**Comment by Remeic** [comment]
> Ah, I just realised that you are using a `next.js` environment 🤦 so sorry. So inside `_app.js` is the place to call the `setup` method. And you are already doing it properly 👍 . So I went back to my sandbox, which is a fork of yours, and I notice that style definition had the color `"red"` in quotes inside the tagged template. That's invalid CSS I believe so I corrected that, restarted the sandbox and it works 🎉 https://codesandbox.io/s/bold-waterfall-ltzpx?file=/pages/index.js
> 
> Can you give it a go and let me know if that helps?

Hi Cristian sorry for delay, in first try my local project had the same error, i restart from scratch and now all work! 
You think that can be useful add codesandbox link in the README ? Maybe for user that want to try out Next + Preact + Goober (  = ❤️ )
