### ISSUE TITLE
Atomic Classes

### ISSUE THREAD

**Issue by trivago-vgarcia** [cristianbote/goober#144]
Would you be interested in allowing to generate atomic classes instead of classes per element?

I'm doing some research to mix the idea of CSS-in-JS with atomic classed, and I think goober is a cool library to add it.

**Comment by cristianbote** [comment]
Hey @trivago-vgarcia! Thanks for opening this issue!

That's a neat idea. Been thinking about it, initially, and I can't remember why I did not went with it.

goober has all the pieces for it to output the atomic classes, because how I see it, we would need to instead of hashing the entire css object, we would go rule by rule/key by key. One thing that might give use some headaches is the @ rules.

**Comment by gc-victor** [comment]
You are right, is prepared to do it. I have started playing with pseudo-classes.

````
 atomic`
    padding: 1em;
    :focus {
        padding: 1em;
    }
    :hover {
        padding: 1em;
    }
`
````

generates these classes

````
.go1143643863:focus{padding:1em;}
.go2834953651:hover{padding:1em;}
.go1668684562{padding:1em;}
````

and returns

`go1668684562 go1143643863 go2834953651`

**Comment by lucat1** [comment]
Atomic classes would be godsent for may applications where styles are duplicated many many times. To make the change beneficial class names would have to be much shorter though. Something like alphabetical ordering would be optimal, but I don't know how hydration on the client side would work then.

**Comment by gc-victor** [comment]
Hey @lucat1!

The length of the classes names is a typical discussion about atomic or utility classes. The increment of the size of the files isn't going to have a significant impact on your application.

Maybe it would be needed to have more explicit names to be easier to read.

I tend to use something like this: `u-display--block` or `u-color--black`.

**Comment by cristianbote** [comment]
Looking back at this, I think goober will for sure not follow the atomic styles approach. The architecture is different and I think for example, otion(https://github.com/kripod/otion) by @kripod has done a fantastic job with it.

Closing this. Thanks @gc-victor for taking the time to explore this, much appreciate it!

**Comment by gc-victor** [comment]
Thanks, Cristian.

For me, it was a starting point for exploring the idea of CSS-in-JS atomic classes. Some months ago, I developed. https://github.com/gc-victor/c-c. A tiny library of CSS-in-JS with atomic classes at run-time and compile-time.
