### ISSUE TITLE
Generate !important to properties

### ISSUE THREAD

**Issue by ijustwanttobecool** [cristianbote/goober#145]
Hi!

Thanks for great tool!

Do you plan option to add !important to every properties. This can be useful in non-save environments, e.g. widget.

**Comment by cristianbote** [comment]
Hey @ijustwanttobecool! Thanks for opening this issue!

I think this should reside on the user facing code. Using `!important` is gonna be messing with the way css works and one would expect to get it to work properly.

Now, for widgets and such, I can see it working fine alongside other css definitions, by targeting that specific widget selector. Do you have some example where this was an issue?

**Comment by cristianbote** [comment]
I haven't heard from the author in a while. Closing.
