### ISSUE TITLE
Unexpected token 'export' on Codesandbox react example

### ISSUE THREAD

**Issue by harshzalavadiya** [cristianbote/goober#149]
### Issue

![image](https://user-images.githubusercontent.com/5774849/83435716-564b2a80-a45a-11ea-9b54-3fbe7ec70a1f.png)

Below Codesandbox is the fork https://github.com/cristianbote/goober#examples react CSB, given in README after updating goober to latest CSB throws error but works fine locally.

This error seems like fairly new since my package https://www.npmjs.com/package/react-multi-select-component (one of the dependent of goober) used to work just fine some days before

### Example
https://codesandbox.io/s/react-goober-p8lg1?file=/src/index.js

### References
Might be related to this https://github.com/codesandbox/codesandbox-client/issues/2679

**Comment by ben-rogerson** [comment]
I'm seeing this issue too - it was working a couple of days before - https://codesandbox.io/s/react-tailwind-styled-components-starter-f87y7?file=/src/App.js

**Comment by cristianbote** [comment]
Hey folks! Thanks for opening this issue!

This is the strangest one yet 🤕 I'm gonna snoop around and see what's the issue. `goober` has not been released recently so it might be an environment issue lurking somewhere. I'll report back.

**Comment by cristianbote** [comment]
Alrighty apparently this is something on codesandbox's side https://github.com/codesandbox/codesandbox-client/issues/4277#issuecomment-637405110

**Comment by harshzalavadiya** [comment]
Thanks @cristianbote,

Closing since not an issue from goober side
