### ISSUE TITLE
 'goober-autoprefixer@latest' is not in the npm registry.

### ISSUE THREAD

**Issue by isakkeyten** [cristianbote/goober#151]
So I was about to use the autoprefixer so i don't do extra steps with postcss and...

```
npm install goober-autoprefixer

npm ERR! 404 Not Found - GET https://registry.npmjs.org/goober-autoprefixer - Not found
npm ERR! 404  'goober-autoprefixer@latest' is not in the npm registry.
```

I checked npmjs.com and it turns out it really isn't out there.

**Comment by isakkeyten** [comment]
Additionally, I'm doing SSR and I'm not using `setup` and everything seems to be working fine? What am I missing? Autoprefixer is beeing injected via setup but setup requires a renderer and I'm just using vanilla template literals, so no renderer at all. How would I go about using the prefixer?

**Comment by cristianbote** [comment]
Hey @isakkeyten! Thanks for opening this issue!

Gah! Indeed, the sub packages are not published with latest. Let me do that right now. That was an oversight on my side.

To answer your second question, if you're using the `setup` in your `app` code, and that app is included on the server I think that'll work as well. Can you share a reproducible codesanbox?

I'll be back when I published the sub-packages with `@latest`.

**Comment by cristianbote** [comment]
Alrighty, `goober-autoprefixer` is published now.

Let me know if you are running into other issues as well.
