### ISSUE TITLE
Possibly unexpected behavior of extractCss() on SSR

### ISSUE THREAD

**Issue by jackyef** [cristianbote/goober#158]
Hi, very nice library you have here! I am currently exploring it more and hoping to be able to use it as my go-to css-in-js solution in the future. Currently, I am finding issues with how the SSR works.

Goober seems to be using a single JS object during SSR to store all the generated styles. The store would be flushed when `extractCss()` is called. https://github.com/cristianbote/goober/blob/master/src/core/get-sheet.js#L2

When doing SSR, this works fine if the server only handle 1 request at a time. Unfortunately, this approach doesn't play well when we introduce some asynchronous tasks during SSR. When this happens, the order of `css` and `extractCss()` calls can vary depending on a lot of factors, basically a race condition.

An example to replicate this issue can be seen here: https://github.com/jackyef/preact-goober-snowpack/blob/master/server/index.tsx#L30

Output:
```
➜  preact-goober-snowpack git:(master) ✗ node .\server\dist\main.js
Koa server listening on port 8001
Welcome, SSR
Welcome, SSR
Welcome, SSR
{
  style: " body{margin:0;font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen','Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',sans-serif;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;} code{font-family:source-code-pro, Menlo, Monaco, Consolas, 'Courier New',monospace;}.go2238624862{text-align:center;}.go3990163120{background-color:#282c34;min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;font-size:calc(10px + 2vmin);color:white;}.go2358084271{height:40vmin;pointer-events:none;margin-bottom:1rem;animation:App-logo-spin infinite 1.6s ease-in-out alternate;}@keyframes App-logo-spin{ from{transform:scale(1);} to{transform:scale(1.06);}}.go2948822817{width:80%;}.go507845381{background:#333333;border-radius:2rem;border:1px solid #282c34;padding:2rem;display:block;width:30vw;margin:2rem auto;text-align:left;}@media only screen and (max-width: 600px){.go507845381 pre{padding:1.25rem;width:auto;}}"
}
{ style: '' }
{ style: '' }
```

Here, we can see that even when we sent 3 requests to the server, only the first request is getting all the extracted CSS rules. The asynchronous task effectively makes the order of operation to be like this:
1. All `css` and `glob` are called for the first request, then waits for the asynchronous task to finish.
2. All `css` and `glob` are called for the first request, then waits for the asynchronous task to finish.
3. All `css` and `glob` are called for the first request, then waits for the asynchronous task to finish.
4. Async task for first request finishes, run `extractCss()`. The single store for ssr css sheet is flushed. Send response back to first request with complete stylesheet.
5. Async task for second request finishes, run `extractCss()`, but the store is flushed already. Server sends response back to second request, with empty stylesheet.
6. Async task for third request finishes, run `extractCss()`, but the store is flushed already. Server sends response back to third request, with empty stylesheet.

### Possible solution
Introduce a separate context to store stylesheet during SSR, so each request can have their own store. 
This might add more complexity for the project, but would allow SSR behavior to be better. Potential issue with this:
1. Code performance -> we'll need to come up with an efficient algorithm to do this
2. Bundle size -> Ideally this shouldn't affect the size of goober module used on client bundle. Adding the new SSR logic in its own separate package/file could be an option, like what react does with `react-dom/server`

**Comment by cristianbote** [comment]
Hey @jackyef, really glad that you've decided to open-up this issue!

Top of my mind, `css` api has the [targets](https://github.com/cristianbote/goober#targets) functionality that usually is used with web components or widgets and such. Do you think this could possibly solve the async nature for the SSR? 🤔

**Comment by jackyef** [comment]
Thanks for the reply @cristianbote !

I looked into `target` and _kinda_ got it to work in user land. I don't really like the way it works though, because it includes:
1. Create a new `ctx` to be used for every request. With react/preact, we can pass this into `Context`
1. Requiring JSDOM on the server to create an element for every request. Assign this as `ctx.target`
2. Manually binding `css` and `glob` calls to use `ctx` so they use `ctx.target`

You can take a look at the changes I made here: https://github.com/jackyef/preact-goober-snowpack/pull/1/files

At the current state, I am not sure if using `target` would be the way to go to tackle this issue.

**Comment by cristianbote** [comment]
Alrighty @jackyef 😄  this really really bother me for a few days and today I had a few moments to open up a PR with another possible solution without `jsdom`.

So here's the breakdown:
1. Create a way to define per context a style collector(https://github.com/jackyef/preact-goober-snowpack/pull/2/files#diff-30e9a907d41138a995360f5257776461R28-R31)
1. If that context is defined `css` and `glob` will pick it up and use it as a target.
1. No need to use `extractCss` anymore cause we've got our scoped style collector and we could use the `.data` attribute https://github.com/jackyef/preact-goober-snowpack/pull/2/files#diff-30e9a907d41138a995360f5257776461R56.

One thing that I failed miserably to describe in my original reply, was that `getSheet` is supposed to return the given `target`. I thought that is the case, but apparently it is not 😞 . So, I need to open up a PR to fix that one.

Let me know how all of this sounds to you.

**Comment by jackyef** [comment]
Hey @cristianbote, really appreciate it!
I have replied to the PR you created there asking specifically about the implementation (which I can't seem to get to work).

Anyway, I think I understand the gist of it. Your implementation made it so we no longer need jsdom, but some manually setup still need to be done on the user-land (setting up custom `css` and `glob` function, binding to the right context). I think users, especially newer users would definitely benefit with something provided by goober out of the box. What do you think?

**Comment by cristianbote** [comment]
Yeah, so for it to be working #162 needs to be fixed. Which is a really easy one -- I just need time 😞

**Comment by cristianbote** [comment]
> I think users, especially newer users would definitely benefit with something provided by goober out of the box. What do you think?

That is a great point! Now, since goober will move to a major version officially I wonder if it'll be a good timing to have the `extractCss` function changed into a `collector` and `context` thing.

**Comment by jackyef** [comment]
> Yeah, so for it to be working #162 needs to be fixed.
Ah I see, I misunderstood that part.

I definitely think it's something that would be good to have in 2.0.0. I would be happy to help contributing if you think it's something I could help with.

**Comment by cristianbote** [comment]
Alrighty, merged in #162. I think we can collectively move on with your idea/proposal 😃 . Also, I think to not weight in the size on the _client_ we could have a separate entry point for this one.

Like:

```js
import { collect } from  'goober/collector';

const getStyleTag = collect();

// later on
console.log(getStyleTag()); // <style id="_goober">html,body{ /* css */ }</style>
```

Just an idea but it's wide open of course 😄

**Comment by jackyef** [comment]
I like the proposed API 👍 . It should be simple enough for users to use. I assume the idea is to have `collect()` automatically do these 2 things right?
1. Do all `css` and `glob` calls
2. Provide a separate context to inject the style sheet into

The only problem right now I think is about how do we automatically do all the `css` and `glob` calls?

**Comment by leader22** [comment]
I've also run into this issue with Next.js using SSG. (minimal repro is [here](https://github.com/leader22/next-goober-extract_css-repro))

I will try https://github.com/jackyef/preact-goober-snowpack/pull/2/files#diff-68f63ff661b86df45182b35a7a34362dR1 later 👀

**Comment by cristianbote** [comment]
Hey @leader22, thank you so much for weighing on this. I'm gonna try your repo as well to see if my above proposal could work 👍

**Comment by leader22** [comment]
That would be great! Thanks in advance. 😉

**Comment by cristianbote** [comment]
@leader22 I've looked into it a bit this morning and this is a strange one, for sure. Locally I get the css generated in each file, but remotely it's not getting included. Still looking into it.

**Comment by leader22** [comment]
FYI: I also tried your fork, but css are not generated even in local.(MBP w/ 4cpus) 😿

**Comment by cristianbote** [comment]
wow! Now that's even more awkward. Wondering why though? 🤔  I've tried it locally with npm/yarn/different node version. Oh wait, could it be next.js version? Just noticed it's latest. I'll explore this one.

**Comment by cristianbote** [comment]
Ok. I think I figured it out. This is a much bigger issue than I anticipated -- still not sure why I don't have it locally though, but oh well.

So what happens is that the `css` call is defined at code runtime, meaning as soon the `Layout` component it's imported that `css` call is getting executed. Now, the quickest solution is to nest that call as part of the `jsx` tree as I did here https://github.com/cristianbote/next-goober-extract_css-repro/commit/03aef7dad69697d23512731422775d3932f81bd3#diff-f09d31e7755c48f1d3dd5d4e7b7bf10d6577114bbf6dd3f2adc142a1cd0bd835.

This is not a problem for _styled_ api though, since the className is generated at render time so it avoids this immediate execution.

Maybe I should add this note on the `css` section, specifying that using it outside the render methods leads to inconsistent results.

**Comment by leader22** [comment]
> So what happens is that the css call is defined at code runtime

Oooh, I see! Thank you for investigating.
(And I realize this is a slightly different with original issue... Sorry to bother you. 😓 )

I've rewritten this style of codes

```js
const Component = () => <div class={style} />;
const style = css({});
```

into this one.

```js
const Component = () => <div class={style()} />;
const style = () => css({});
```

And everything works fine. 🙌 

> Maybe I should add this note on the css section

Would you mind me sending PR for docs?

**Comment by cristianbote** [comment]
Please do! Much appreciate it! Thank you!
