### ISSUE TITLE
Add support for web-components

### ISSUE THREAD

**Issue by cristianbote** [cristianbote/goober#17]
This is all @michael-klein's initiative 😄to add support for web-components with a parametrized _target_ for `styled`.

@michael-klein feel free to add more details. I've created this, to just put it on the roadmap 💯

**Comment by michael-klein** [comment]
Hey there :)

So, for web-components, a single global style sheet obviously doesn't work, due to shadow DOM. Therefore, goober would need a mechanism to render to different targets (like the shadowRoot of a web component).

I played with a few ways to implement this and my current favorite is to do it by means of a function binding on styled (which would pass the target to the functions that need it). This change would also incorporate setting the pragma this way and do away with setPragma ([htm](https://github.com/developit/htm) is the inspiration for this idea).

Basically, users would bind like this to change the target and/or pragam:
```javascript
styled = styled.bind({
     h: somePragma,
     target: this.shadowRoot // in case of a web-component
})
```

I have this change already implemented in a branch and it actually shaves off some bytes from the bundle size. The implementation is mostly in styled.js:
```javascript
export const styled = function(tag) {
  let context = this || {};
  const h = context.h;
  let target = context.target || (document && document.head);
  return (str, ...defs) => props => {
    const className = getClassNameForCss(getCss(str, defs, props), target);

    // To be used for 'vanilla'
    if (!h || !tag) return className;

    return h(
      tag,
      Object.assign({}, props, {
        className:
          (props && props.className ? props.className + " " : "") + className
      })
    );
  };
};
```
and sheet.js
```javascript
export const add = (hash, css, target) => {
  // If this is already present just stop
  if (styles[hash] == css) {
    return;
  }

  // Keep the hash and the value in _cache_
  styles[hash] = css;

  // If we're no the client
  if (target) {
    let sheet = target.querySelector("style[" + SHEET_ID + "]");
    if (!sheet) {
      sheet = document.createElement("style");
      sheet.setAttribute(SHEET_ID, "");
      target.appendChild(sheet);
    }

    if (!sheet.firstChild) {
      sheet.appendChild(document.createTextNode(""));
    }

    // Append the css into the style sheet
    sheet.firstChild.data += css;
  }
};
```

**Comment by cristianbote** [comment]
Hey @dan-harris! 😄
I know you've _really_ liked the `setPragma` paradigm. @michael-klein is proposing something like `htm` https://github.com/developit/htm, where you'll have to bind the `styled` method. Do you see any concerns? What's your feedback be for this breaking change?

```js
setPragma(h);

// will turn into

styled.bind({ h });
```

**Comment by dan-harris** [comment]
Hey @cristianbote 👋. Kudos again for a very cool library! 
Also great stuff @michael-klein 🙌.
You guys da real MVP.

I think the bind method is nice 👍. No problems with this over `setPragma` . Have vaguely played with htm/preact (but not in a production environment)... so admittedly, I feel like my authority to comment on this is a little low... 

Also, gave me a random idea.
Not 100% sure on whether it makes sense (or if theres much point to it over other methods), but using the `target` property I could possibly use goober in a static render situation (e.g. server-side templates from things like node/aspnet/PHP .etc). That's kinda cool to introduce scoped partial templates 🤷‍♀️. 

e.g.

```html
<!-- some templating language -->
<my-partial-template class="some-goober-hash"></my-partial-template>
```

```js
// some attached js
styled.bind({ target: document.querySelector('my-partial-template') })
```

**Comment by cristianbote** [comment]
Awesome @dan-harris! Thank you! Really appreciate your feedback. Stay tuned and/or join the party! 😄

**Comment by michael-klein** [comment]
Sounds cool! I'm currently trying to finish  the implementation. It works already but I'm looking for ways to shave off some bytes if I can (though it's still under 1kb)

**Comment by geocine** [comment]
@michael-klein is there a documentation on how to use this?

**Comment by cristianbote** [comment]
Hey @geocine, check out this tweet https://twitter.com/cristianbote_/status/1100513333940240384?s=20 and also the readme section on vanilla css https://github.com/cristianbote/goober/blob/master/README.md#csstaggedtemplate.

Let us know if there's more info you need on using it.
