### ISSUE TITLE
publish latest `gatsby-plugin-goober`

### ISSUE THREAD

**Issue by cusxio** [cristianbote/goober#171]
## Current Behaviour

Currently, the latest version of `goober` on `npm` is v2.

`gatsby-plugin-goober` however, is still using v1. This causes an error, i.e. `setPragma is not a function`

i.e. `gatsby-plugin-goober` `2.1.0` should be the `latest` version to match `goober`.

https://www.npmjs.com/package/gatsby-plugin-goober

**Comment by cristianbote** [comment]
Hey @cusxio you are right 😞 . On it!

**Comment by cristianbote** [comment]
Should be fixed now. Let me know if you run into more issues.

**Comment by cusxio** [comment]
All good! 👍
