### ISSUE TITLE
Keyframes support

### ISSUE THREAD

**Issue by dvoytenko** [cristianbote/goober#178]
Are there any good examples of `@keyframes`? I tried a couple of options, but presently cannot figure out how to obfuscate the keyframes name.

I tried this:

```
const keyframes = css`
  @keyframes rotate {
    from {
      transform: rotate(0deg);
    }
    to {
      transform: rotate(360deg);
    }
  }
`;

const myButton = css`
  animation: 4s linear 0s 2 alternate rotate;
`;
```

And another nit is that `const keyframes` in my example doesn't appear to be used by reference anywhere and can be removed by DCE.

Is there a better way to do this?

**Comment by cristianbote** [comment]
Hey @dvoytenko thank you so much opening this issue.

>_but presently cannot figure out how to obfuscate the keyframes name._

That is something that `goober` doesn't do. We take the input, if it's a string we convert it to an object, and basically construct the css definitions, and hash-ing the classnames along the way to match each definition. So far I did not need to obfuscate/hash the animation name 🤔  do you see yourself needing that? I would love to learn about the where and why if you can.

In your above example, indeed, that `keyframes` const will get removed, but there are couple different ways you could define the animations depending on your need:

1. As part of the `css` call:
```js
const myButton = css`
  animation: 4s linear 0s 2 alternate rotate;

  @keyframes rotate {
    from {
      transform: rotate(0deg);
    }
    to {
      transform: rotate(360deg);
    }
  }
`;

<button class="${myButton}">
  Label
</button>
```

This will append/prepend the `@keyframes` rule to the stylesheet only if/when the `css` is called.

2. Define it as part of `glob`(global) call:
```js
import { css, glob } from 'goober';

// The global call is usually called at the 'root' of your app
// but there's nothing stoping one to call it where it's needed
glob`
  @keyframes rotate {
    from {
      transform: rotate(0deg);
    }
    to {
      transform: rotate(360deg);
    }
  }
`;

const myButton = css`
  animation: 4s linear 0s 2 alternate rotate;
`;

<button class="${myButton}">
  Label
</button>
```

And I think I can come up with all kinds of different patterns 😄  but I'll wait your reply to see if this fits your use case.

**Comment by dvoytenko** [comment]
The Emotion's keyframes approach comes to mind here. It's very similar to `css''`, except it looks like this:

```
const rotate = keyframes`
  from {
    ...
  }
  to {
    ...
  }
`;

const myButton = css`
  animation: ${rotate} 1s;
`;
```

I think adding something like this on top of the `css''` you already have should be fairly straightforward. There are a few benefits vis-a-vis to the existing approaches that you list:

1. An `export const rotate = keyframes...` like this can be imported and used for many declarations. The dependency graph would be clear from import graph and that'd give a lot of opportunities for DCE and other optimizations.
2. No need for namespacing keyframe names. The same mechanism that you already have for `css''` can be used for generating unique IDs. And it'd be pretty much automatic.

**Comment by cristianbote** [comment]
Oh, I would love that! 👍  Great points about the reusability aspect. The syntax `animation: ${name} 1s;` actually makes 100% sense. I'm gonna start working on it asap 😄  looks really dope! Thank you!

**Comment by cristianbote** [comment]
Added in `goober@2.0.6`
