### ISSUE TITLE
Compatibility with styled-system

### ISSUE THREAD

**Issue by donysukardi** [cristianbote/goober#186]
I was trying out goober with `styled-system` and found out that it's not working. Is compatibility with `styled-system` something `goober` will be looking to adopt?

https://codesandbox.io/s/goober-x-styled-system-not-working-4lywf?file=/src/index.js

**Comment by donysukardi** [comment]
I found out that it's been discussed here - https://github.com/cristianbote/goober/issues/136. Any plan to make it work without work around?

**Comment by cristianbote** [comment]
Hey @donysukardi!

You mean, to not have to write the styles as objects? So the tagged templates would interpolate the data?

Pasting here the example from your codesandbox:
```jsx
const Box = styled("div")`
  ${color}
`;

const WorkaroundBox = styled("div")((p) => ({
  border: 0,
  ...color(p)
}));
```

I'll look into it. I have some more size space to work with and maybe I can find a way to squeeze this one as well. Keep you posted.

**Comment by cristianbote** [comment]
Alrighty. I think it turned out decent enough for `+5B`. 👍

**Comment by cristianbote** [comment]
Available in `2.0.9`

**Comment by cristianbote** [comment]
here's your sandbox with the new version https://codesandbox.io/s/goober-x-styled-system-not-working-forked-q06gr?file=/src/index.js

**Comment by donysukardi** [comment]
AWESOME POSSUM @cristianbote! 🎉🎉🎉

**Comment by ayoubphy** [comment]
> here's your sandbox with the new version https://codesandbox.io/s/goober-x-styled-system-not-working-forked-q06gr?file=/src/index.js

I checked the sandbox, something is not working correctly, while the styles are working, the html elements have the attributes on them.
