### ISSUE TITLE
css prop functionality as part of babel-plugin and macro

### ISSUE THREAD

**Issue by cristianbote** [cristianbote/goober#209]
Examples:
- emotion https://emotion.sh/docs/css-prop
- styled-components https://styled-components.com/docs/api#css-prop

**Comment by cristianbote** [comment]
Jus discovered this https://github.com/agneym/babel-plugin-goober-css-prop 😲 awesome job @agneym! I'll add it to the list of integrations if you don't mind.

Thank you!

**Comment by agneym** [comment]
Sure 😄 I made this so I could try out `tw` prop offered by [twin.macro](https://github.com/ben-rogerson/twin.macro). 

[sample repo](/agneym/next-goober-twin)

I haven't tried out other use cases for it though, hopefully it works for others 😅

**Comment by cristianbote** [comment]
I might be able to look more into it and test it, but meanwhile feel free to open a PR to add it in here https://github.com/cristianbote/goober#integrations ✌️
