### ISSUE TITLE
Explanation of difference between CSS object and template string

### ISSUE THREAD

**Issue by alexieyizhe** [cristianbote/goober#214]
In the [`css` prop section](https://github.com/cristianbote/goober#using-css-with-jsonobject), it states:
> Notice: using `css` with object can reduce your bundle size.

I'm just curious as to what that means, and how/why that's the case

Great work btw!

**Comment by cristianbote** [comment]
Hey @alexieyizhe! Happy New Year! 🎉  Thanks for opening this issue.

So, by using tagged templates, usually the transpiler would convert those either into some sort of a combination between arrays and a reduce function and also preserve the newlines, indentations and such. With objects you do not get the object structure changed, but rather neatly minified.

Lately though, if you bundle modern syntax, and tagged templates, in their original form, gzipped code tends to be in the same range. For example, on a project built with [wmr](https://github.com/preactjs/wmr) I get `-1KB` when switching from tagged templates to objects.

Hopefully this clears it out.

Do you think changing the wording might be better?

**Comment by alexieyizhe** [comment]
Ah, that makes a lot of sense. I think adding a bit of clarification would be cool, but maybe even linking to this issue would suffice? I'm not too opinionated.

Thank you for explaining - feel free to close this whenever!

**Comment by cristianbote** [comment]
Awesome! will add the link to the readme. Thanks!
