### ISSUE TITLE
"import" export target is recognized as CJS in node@12.19+

### ISSUE THREAD

**Issue by natemoo-re** [cristianbote/goober#215]
Goober uses node's `exports` feature in `package.json` and includes the following line:
```json
"import": "./dist/goober.module.js",
```

While `./dist/goober.module.js` is in fact in ESM format, `node@12.19+` attempts to parse it as CJS because it uses a standard `.js` extension. Switching this the node-supported `.mjs` extension would make Goober usable in ESM node projects.

**Comment by cristianbote** [comment]
Hey @natemoo-re that is a great suggestion! Definitely need to do it. On it! Thank you!

**Comment by cristianbote** [comment]
This should be fixed now. Let me know if this is still an issue @natemoo-re! Thank you for raising this. 🙏
