### ISSUE TITLE
Missing type support for goober/global ?

### ISSUE THREAD

**Issue by mimiqkz** [cristianbote/goober#219]
I was trying to use `createGlobalStyles`, by importing it as `import {createGlobalStyles} from 'goober/global'` into my nextjs typescript project. However, I got the error `Could not find a declaration file for module 'goober/global'.`

**Comment by cristianbote** [comment]
Hey @mimiqkz thank you for opening this issue!

You are right 😞  the types are missing. Gonna add them and push a new version with them. Really sorry for this.
