### ISSUE TITLE
Preact cli plugin to extract styles

### ISSUE THREAD

**Issue by gerhardsletten** [cristianbote/goober#228]
I anyone need to extract styles in a preact cli application I made a plugin which does that.

[gerhardsletten/preact-cli-goober-ssr](https://github.com/gerhardsletten/preact-cli-goober-ssr)

**Comment by cristianbote** [comment]
This is amazing @gerhardsletten! Would you like to open a PR to have it included in the `README`?

**Comment by gerhardsletten** [comment]
@cristianbote Thanks, Goober is also even more amazing, with the joy of writing css-in-js without bundle-bloat ;-)

Maybe it should be added below a `Ecosystem` section?

**Comment by cristianbote** [comment]
@gerhardsletten how do you feel about placing it in here https://github.com/cristianbote/goober#integrations? 🤔
