### ISSUE TITLE
Missing types on theme when using a theme

### ISSUE THREAD

**Issue by kerimhudson** [cristianbote/goober#243]
I have a setup using Preact and Goober on Snowpack, and noticed that when using a theme within `setup`, type definitions are missing when using the `styled` function.

There's probably a smarter way of adding this in, but wanted to raise it. I'm not sure the best approach to perhaps adding this in, but I managed to get it working doing the following: 

```
import { Properties as CSSProperties } from "csstype";

interface Theme {
  typography: {
    fontSize: {
      small: string;
    };
  };
}

export = goober;

export as namespace goober;

declare namespace goober {
  interface StyledFunction {
    // used when creating a styled component from a native HTML element
    <
      T extends keyof JSX.IntrinsicElements,
      P extends Object = { theme: Theme }
    >(
      tag: T
    ): Tagged<JSX.LibraryManagedAttributes<T, JSX.IntrinsicElements[T]> & P>;

    // used to extend other styled components. Inherits props from the extended component
    <PP extends Object = {}, P extends Object = { theme: Theme }>(
      tag: StyledVNode<PP>
    ): Tagged<PP & P>;

    // used when creating a component from a string (html native) but using a non HTML standard
    // component, such as when you want to style web components
    <P extends Object = { theme: Theme }>(tag: string): Tagged<
      P & Partial<JSX.ElementChildrenAttribute>
    >;

    // used to create a styled component from a JSX element (both functional and class-based)
    <
      T extends JSX.Element | JSX.ElementClass,
      P extends Object = { theme: Theme }
    >(
      tag: T
    ): Tagged<P>;
  }

  const styled: StyledFunction;
  function setup<T>(
    val: T,
    prefixer?: (key: string, val: any) => string,
    theme?: Function
  ): void;
  function extractCss(): string;
  function glob(
    tag: CSSAttribute | TemplateStringsArray | string,
    ...props: Array<string | number>
  ): void;
  function css(
    tag: CSSAttribute | TemplateStringsArray | string,
    ...props: Array<string | number>
  ): string;
  type StyledVNode<T> = (props: T, ...args: any[]) => any;
  type Tagged<P extends Object = {}> = <PP extends Object = {}>(
    tag:
      | CSSAttribute
      | TemplateStringsArray
      | string
      | ((props: P & PP) => CSSAttribute | string),
    ...props: Array<
      | string
      | number
      | ((props: P & PP) => CSSAttribute | string | number | undefined)
    >
  ) => StyledVNode<Omit<P, "theme"> & PP>;
  interface CSSAttribute extends CSSProperties {
    [key: string]: CSSAttribute | string | number | undefined;
  }
}
```

**Comment by cristianbote** [comment]
Hey @kerimhudson, thanks for opening this issue!

I wish I could help you with this but my typescript it's not that good, yet! 😅 Wondering if @devrnt has some more experience with this?

**Comment by devrnt** [comment]
Good morning (for me anyway) @kerimhudson 

Yes indeed there is a more suitable way, see https://github.com/cristianbote/goober/blob/master/ts-tests/test-api.tsx#L6

Comes down to creating your own declaration file (e.g. `goob.d.ts`) where you extend the theme (`DefaultTheme`) interface. If you have problems, hit me up!

@cristianbote I think this should be mentioned in the docs, but I recall having a "TypeScript" section in the docs right?

**Comment by kerimhudson** [comment]
Thanks @devrnt and @cristianbote, that makes more sense. Sorry, I just couldn't work it out. I don't see typescript in the docs, most of my setup I've been finding via the issues on Github. Perhaps there'd be some room to add to them. Might give it a go and submit a pull request.

**Comment by devrnt** [comment]
@kerimhudson Seems fine on my part, everything about this topic should be mentioned here: https://github.com/cristianbote/goober/pull/193

**Comment by kerimhudson** [comment]
@devrnt And where is it in the docs? I don't seem to see it there or on the README. I meant specifically for adding them.

**Comment by devrnt** [comment]
Right know nothing is mentioned in the README. I gave you the PR that contains a briefly explanation of extending the theme that could be used for your PR 😀

**Comment by kerimhudson** [comment]
Ah okay perfect. I just misunderstood you then as I saw a mention of adding it to the README there so thought that perhaps meant you were in the process of doing so. I'll close this for now then, and try and get that PR up later.

Thanks @devrnt and @cristianbote for the awesome work on goober. Been really enjoying it so far!

**Comment by cristianbote** [comment]
Awesome @kerimhudson, thank you!
