### ISSUE TITLE
Missing type definitions for tagged template literals syntax

### ISSUE THREAD

**Issue by gustavoaz7** [cristianbote/goober#244]
Hello there,

I've recently found this library when looking for a lightweight alternative for css-in-js and started using it in a TS project. After setting it up babel plugin to use tagged template literals I found out it was not possible due to lack of type definitions.

<img width="711" alt="Screenshot 2021-01-22 at 10 38 23" src="https://user-images.githubusercontent.com/28453820/105473919-f7168080-5c9d-11eb-8508-a229c726ff19.png">

I'll continue using it with default syntax as I see much value in this library but adding support for tagged template literals would be highly appreciated :)

**Comment by cristianbote** [comment]
Hey @gustavoaz7 thanks for opening this issue!

Uh, oh. Let me look into it. Should be possible to cover this.

**Comment by PrinceSumberia** [comment]
Hi @gustavoaz7, 

Try `import { styled } from 'goober/macro'` as mentioned here: https://goober.js.org/integrations/babel-macro-plugin. This worked for me.

**Comment by cristianbote** [comment]
I believe this got fixed. @gustavoaz7 let me know if you still have issues with this.
