### ISSUE TITLE
Incorrect prefixer behavior with `position: sticky`

### ISSUE THREAD

**Issue by xxczaki** [cristianbote/goober#247]
Goober's built-in prefixer does not work correctly with `position: sticky;`. It changes it to: `position: -webkit-sticky, sticky;`, which is incorrect and breaks the element (it is no longer sticky).

<img width="189" alt="Zrzut ekranu 2021-02-1 o 10 00 34" src="https://user-images.githubusercontent.com/22645979/106436401-5598e700-6474-11eb-8001-034a1bc4d2b0.png">

I'm using the `styled` API with the latest version of Goober with Next.js v10 and Preact. Using React does not change anything.

**Comment by cristianbote** [comment]
Hey @xxczaki thanks for opening this issue!

Indeed it's a bug! Gonna fire up a PR to fix this.
