### ISSUE TITLE
CSS Grid Invalid property when using Prefixer

### ISSUE THREAD

**Issue by kerimhudson** [cristianbote/goober#251]
When using the included prefixer, CSS Grid properties do not render in chrome with the error `invalid property value`.

**How to test:**

Setup goober with prefixer:
```
import { prefix } from "goober/prefixer";
setup(h, prefix, useTheme);
```

Create a div with CSS grid:

```
styled('div')`
display: grid;
grid-template-columns: repeat(12,1fr);`
```

The div will not render the columns with invalid property value in chrome.

**Comment by cristianbote** [comment]
Hey @kerimhudson, thank you for opening this issue. You are correct! This was an issue, and just last night I've discovered it 😬 and pushed a new fix. So, you should use the latest `^2.0.33`.

Here's a csb link https://codesandbox.io/s/kind-sky-69em4?file=/src/index.js.

Let me know if this fixes your problem 👍

**Comment by kerimhudson** [comment]
What a difference once evening makes! 

Yes, all good now on `2.0.33`. Great work, as always Cristian!
