### ISSUE TITLE
Function components cannot be given refs.

### ISSUE THREAD

**Issue by Crisis2010** [cristianbote/goober#257]
Hello! I'd like to move from styled-components to goober, but can't fix one issue:

`Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

Here is example:
https://codesandbox.io/s/react-goober-forked-w3dh2?file=/src/index.js

i've tried many things, but `console.log(ref)` is always undefined, instead of el
What i'm doing wrong?

**Comment by cristianbote** [comment]
Hi @Crisis2010, thanks for opening this issue.

Since `goober` is agnostic of your virtual dom, jsx, library of choice,`styled` supports a second argument that is the reference for your library `forwardRef` API. In your case you need to pass `React.forwardRef` as the second argument to the components that you need your ref to:

```jsx
const Title = styled("h1", React.forwardRef)`
  font-weight: bold;
  color: dodgerblue;
`;
```

Let me know if this helps. Cheers!

**Comment by Crisis2010** [comment]
Yeah, thanks! Tried everything except this)

It seems to me that it will not be superfluous to indicate this more explicitly in the documentation.

**Comment by cristianbote** [comment]
Hey @Crisis2010, oh you are right! It should totally be reflected in the docs. Right now it only appears only as part of the documentation of `styled` function https://github.com/cristianbote/goober#styledtagname-string--function-forwardref-function I believe another example in that section would help. Would you like to add it? 😄 I would be really grateful! 🙏

**Comment by mpkelly** [comment]
@cristianbote I needed this too and didn't spot it in the docs. So I have added an example to make it more obvious and sent you a PR. It would be handy to keep this param of `styled` but allow a default as part of the `setup` call. I could send you a PR later for that, if you want?

Also have a question: does goober have an equivalent of [.attrs](https://styled-components.com/docs/api#attrs) from styled-components? I am looking for a way to add/remove props that the component receives.

**Comment by cristianbote** [comment]
Awesome work @mpkelly! Thanks for opening the PR.

As for the `.attrs` api, there's no equivalent in goober. I believe there should be a hard line between _Styled_ components and regular ones and I feel strange about `.attrs` 😄  it's like a _pre_-processor for your props but shouldn't that functionality exist inside the functional components instead? I don't know, I really think we should keep these things separated.

Anyway in goober the equivalent would be to have a `InputStyled` that handles the styling and the main `Input` component handling the type and size. Like so:

```jsx
import { styled } from "goober";

const InputStyled = styled("input")`
  border-radius: 3px;
  border: 1px solid palevioletred;
  display: block;
  margin: 0 0 1em;
  padding: ${(props) => props.padding};

  ::placeholder {
    color: palevioletred;
  }
`;

const Input = ({ small, ...props }) => {
  return <InputStyled type="text" size={small ? 5 : undefined} {...props} />;
};
```

Running the above in here https://codesandbox.io/s/loving-gareth-n3vtx?file=/src/App.js:23-403

**Comment by mpkelly** [comment]
@cristianbote thanks for taking time to write the example! You're right that this is a general problem and not something that should necessarily be in the library. I actually wrote a HOC that allows me to control the final props and that worked well in this case. It was just that I had used goober v1 a year or so ago and thought I remembered being able to do something similar to `.attrs` - but likely not then!

**Comment by jjjtoikka** [comment]
@cristianbote this does not work, if we take it a bit further...
So I have styled component and it's used in normal component. Now I want to use this generic component elsewhere, then the attributes or styles disappears depending on the use case. Any ideas for this?

// base component
```
export const StyledContainer = styled(
  'div',
  React.forwardRef
)<Props>((props) => {
   // style here
});

export const Container = forwardRef(
  (
    {
      // props here
    }: Props,
    ref?: Ref<HTMLDivElement>
  ) => {
    const props = {
      // props here
    };
    const attrProps = {
      // attrs here
    };
    return <StyledContainer ref={ref} {...props} {...attrProps} />;
  }
);
```
// using base component and extending it with style
```
// extend component
const StyledEl = styled(Container)<Props>(({ props }) => ({
  // ...style here
  // attr props comes, but no style
}));

// extend with only styled component
const StyledEl = styled(StyledContainer)<Props>(({ props }) => ({
  // ...style here
  // styles comes, but no attr props
}));

<StyledEl as="span" {...props} {...attrProps} />
```

Cheers, J

**Comment by jjjtoikka** [comment]
Hmm, again I was a bit too hasty. You can circumvent it with:
```
const attrProps = {
    // attrs here
    // like className etc
};
<StyledEl as="span" {...props} {...attrProps} />
```
