### ISSUE TITLE
[Discussion] Question about setup placement

### ISSUE THREAD

**Issue by mkhbragg** [cristianbote/goober#261]
**This is not an issue**

👋  thanks so much for creating this super-light styling library - I love it so far and have not yet missed emotion since switching. Reading the goober documentation, I understand that `setup` needs to be called before `styled` can be used. I tried using `setup` in each of my Storybook `**.stories.tsx` files, with success, but then I created a component that needed access to `shouldForwardProp`. This means that I will need to either (a) call `setup` in each component file so that each component knows what props should be forwarded, or (b) I should call `setup` at the root of whatever is consuming these components, for example Storybook or a React app, and pass the entire list of props that should not be forwarded for all components. 

Is the expectation that each component calls `setup` individually? It wasn't clear from the docs. I'm using theming, so calling setup with the default theme for each component will add a little bit of extra weight, but given how light goober is already it's a small price to pay. I just want to make sure I'm doing things right.

Sorry if this is a noob question. Thanks!

**Comment by cristianbote** [comment]
Hey @kerimhudson, thank you soo much for your kind words! 🙏 

That `setup` function was born out of a way to make sure that `goober` is agnostic of one's virtual dom library implementation. With that time the `setup` became more of a way to bootstrap and internally setup `goober`.
So, I usually call `setup` just once, at the root of the entry point for the given app.

Is there a way to hook or call some bootstrap code on Storybook? Before the components are rendered? I'm not that familiar with Storybook sadly.

**Comment by mkhbragg** [comment]
Ah ok, thank you @cristianbote! Thank you for explaining - it sounds like I will need to [create a decorator](https://storybook.js.org/docs/react/writing-stories/decorators#global-decorators) that runs the `setup` code.
