### ISSUE TITLE
🚨 Breaking change in 2.0.34

### ISSUE THREAD

**Issue by jakehamilton** [cristianbote/goober#263]
# Description

It looks like between 2.0.33 and 2.0.34 `glob` was removed from Goober. Since this is a patch change, anyone pinning `goober@^2.0.0` will still receive it. This just hit us for a non-mission-critical page (thankfully).

# What's Happening?

Using `import { glob } from "goober"` is failing when upgrading from `2.0.33` to `2.0.34`.

# Expected Result

Upgrading patch versions should not introduce breaking changes.

# Possible Resolutions

I think the best way forward is to republish `2.0.33` as a newer version `2.0.35`. Then to take the new changes up a major version since they introduce a breaking change. So tagging `2.0.34` as `3.0.0`.

**Comment by cristianbote** [comment]
Oh, darn it 😢 totally got sidetracked and forgot that I was planning that removal 😬.

Thank you so much for your suggestions, will revert and publish `2.0.35` with the `glob`.

**Comment by cristianbote** [comment]
Oh, btw, you could switch by now to `createGlobalStyles` https://goober.js.org/api/createGlobalStyles

**Comment by cristianbote** [comment]
OR directly import `glob` from `goober/glob`

**Comment by cristianbote** [comment]
@jakehamilton just published `2.0.35` with the `glob` as part of the core again. Let me know if there's anything else.

Thank you so much.

**Comment by jakehamilton** [comment]
Hey @cristianbote!

Thanks for the quick help 🙏
I saw `createGlobalStyles` in the docs, will look at moving to that. Though this piece isn't my team's direct focus at the moment so it may wait a bit. Appreciate you reverting things!

---

Looks like the latest version fixes things!
