### ISSUE TITLE
goober/prefixer README mentions `tiny-css-prefixer` but `style-vendorizer` is used.

### ISSUE THREAD

**Issue by danielweck** [cristianbote/goober#270]
The documentation is out of date:

https://github.com/cristianbote/goober/blob/master/prefixer/README.md#goober-autoprefixer

See commit:

https://github.com/cristianbote/goober/commit/6fe8d8e5c099af6b1222c9e75d89229a360736be#diff-16bbea0941db4db79d82934c8d028244bd83d653f15d800015daa4d0dd631cd3

**Comment by cristianbote** [comment]
Oh, thank you so much @danielweck! Indeed. Feel free to open a PR to address it. It's more than welcomed. 👍

**Comment by kudnx** [comment]
Good day, can i pick this up?

**Comment by danielweck** [comment]
> Good day, can i pick this up?

Feel free, unfortunately I do not have the bandwidth for this :) Thanks!

**Comment by kudnx** [comment]
@danielweck Thank you!

**Comment by cristianbote** [comment]
Closed in #272
