### ISSUE TITLE
Styling custom component?

### ISSUE THREAD

**Issue by mkhbragg** [cristianbote/goober#273]
Does goober support styling of another React component? For example:

```tsx
import { FancyIcon } from 'icon-library'

export const FancyComponent = (props) => (
    <FancyIconView size={14} />
)

const FancyIconView = styled(FancyIcon)`
  position: absolute;
`
```

When I use the code above, `FancyIcon` is rendered correctly, but `position: absolute` is not applied. Is this by design or is this a bug?

Adding `style={{ position: 'absolute' }}` to `FancyIconView` in `FancyComponent` works, but I would prefer to use goober.

Thank you! I really appreciate this library 🙏

**Comment by cristianbote** [comment]
Hey @mkhbragg, so sorry for my late reply!

It should work seamless, as long as `FancyIcon` accepts a `className` as prop. Here's an example with `FancyIcon` defined locally https://codesandbox.io/s/friendly-pine-uh1x4?file=/src/App.js.

Let me know if this worked for you.

**Comment by mkhbragg** [comment]
Ahh, accepting `className` as prop on `FancyIcon` was the missing piece. Thank you so much! 💛
