### ISSUE TITLE
Missing types for `styled` with array of functions

### ISSUE THREAD

**Issue by steschwa** [cristianbote/goober#275]
## Problem

The documentation has an example that allows passing an array to the `styled` function whose items can also be a function  (https://goober.js.org/api/styled#arrays). Unfortunately the current TS typings do only allow an array of `CSSAttribute` (https://github.com/cristianbote/goober/blob/master/goober.d.ts#L70).

## Example

```ts
type ButtonProps = {
  isLoading?: boolean
}

styled("button")<ButtonProps>([
  { color: "red" },
  ({ isLoading }) => ({ color: "blue" }) // 👈 TS complains about `({ isLoading }) => ({ color: "blue" })` is not assignable to `CSSAttribute`
])
```

## Fix

A simple solution would be to just extend the existing `CSSAttribute[]` [here](https://github.com/cristianbote/goober/blob/master/goober.d.ts#L70) to also accept a function:

```ts
type StylesGenerator<P extends Object = {}> = (props: P) => CSSAttribute | string
type Tagged<P extends Object = {}> = <PP extends Object = {}>(
        tag:
            | CSSAttribute
            | (CSSAttribute | StylesGenerator<P & PP>)[]
            | TemplateStringsArray
            | string
            | StylesGenerator<P & PP>,
        ...props: Array<
            | string
            | number
            | ((props: P & PP) => CSSAttribute | string | number | false | undefined)
        >
    ) => StyledVNode<Omit<P & PP, keyof Theme<DefaultTheme>>>;
```

If you want i would be happy to open a PR!

**Comment by cristianbote** [comment]
Hey @steschwa, thanks for opening this issue and looking at the issue as well. I would appreciate the PR for sure! 🙏 Thank you!
