### ISSUE TITLE
Should I use goober setup once or on every component?

### ISSUE THREAD

**Issue by pure-js** [cristianbote/goober#279]
I want to clarify whether you need to use `setup` on each page or once for the entire SPA?
```javascript
import React from 'react';
import { setup } from 'goober';

setup(React.createElement);
```

**Comment by cristianbote** [comment]
Hey @pure-js, only once at the root of your app. Gonna update the docs and readme to reflect this as well. Thanks for pointing it up! 😃 If you want feel free to open the PR yourself. 👍
