### ISSUE TITLE
Typings

### ISSUE THREAD

**Issue by cristianbote** [cristianbote/goober#28]

**Comment by pmkroeker** [comment]
I'm working on this currently! I'll submit a PR hopefully in the next few days that at least adds some basic typings to the exports!

**Comment by cristianbote** [comment]
Thank you! 😄You rock!

**Comment by pmkroeker** [comment]
Opened PR #33 !

**Comment by pmkroeker** [comment]
PR #33 is considered feature complete. At least for the time being. The good thing is that updating the typings to allow camelCase instead of strictly kebab-case should be straight forward if that implementation goes ahead.

**Comment by pmkroeker** [comment]
This can be closed #33 .

Thanks!
