### ISSUE TITLE
`styled` API missing `as` prop TS type definition

### ISSUE THREAD

**Issue by andreipfeiffer** [cristianbote/goober#282]
When using the `styled` API, the `as` prop works as expected, but the TS type definition is missing from the definition file.

<br />

<img width="917" alt="Screenshot 2021-04-11 at 17 24 35" src="https://user-images.githubusercontent.com/2570562/114308112-5e98db00-9aeb-11eb-82c5-4245bac419d3.png">

**Comment by cristianbote** [comment]
That's a good catch @andreipfeiffer! Thanks for opening this issue 🙏
