### ISSUE TITLE
next.js template

### ISSUE THREAD

**Issue by cristianbote** [cristianbote/goober#30]
Create a next.js template, to make it easier for people to adopt it.

**Comment by timgivois** [comment]
@cristianbote The template should be in codesandbox? Is there any specific example on how to use it? Could you give more details?

**Comment by cristianbote** [comment]
Hey @timgivois! Thanks for asking! Basically I was thinking to have an example repo, like `styled-components` has in here https://github.com/zeit/next.js/tree/canary/examples/with-styled-components.

It wouldn't be _that_ different. We would basically need to call `extractCss` and put it in a style tag. 😄

**Comment by timgivois** [comment]
Cool, gonna work on that @cristianbote

**Comment by cristianbote** [comment]
https://github.com/vercel/next.js/pull/15070

**Comment by DominicTobias** [comment]
> vercel/next.js#15070

Thanks! This library seems awesome just what I’ve been hoping for, though the last comment in that issue seems like it’s a no-go for nextjs if it’s bundled into each chunk 🤔

**Comment by glassdimlygr** [comment]
Any update for 2022?

**Comment by cristianbote** [comment]
Hey @glassdimlygr what sort of update are you looking for? 🤔 If there's a next.js template? There is https://github.com/vercel/next.js/tree/canary/examples/with-goober
