### ISSUE TITLE
Add support for camelCase to dash-case transformation for objects

### ISSUE THREAD

**Issue by cristianbote** [cristianbote/goober#31]
I've tried adding it, but it went over the `1000B` so it's under our target. It's not that _difficult_ to add support for it, basically here: https://github.com/cristianbote/goober/blob/master/src/core/parse.js#L37 we should just do a regex transform.

**Comment by cristianbote** [comment]
FIxed in https://github.com/cristianbote/goober/commit/e70513e045ee29f5187df22584ec7a4e7b4888c8

**Comment by pmkroeker** [comment]
I can update the typings to support this for people who use the object notation with typescript

**Comment by cristianbote** [comment]
Sweeet! 😄
