### ISSUE TITLE
using keyframes with shadow dom

### ISSUE THREAD

**Issue by stepan-dashkevich** [cristianbote/goober#323]
I'm trying to set up preact + goober (latest) app which should mount into shadow DOM.
```
import { h, render } from 'preact'
import { setup } from 'goober'
import * as goober from 'goober'

setup(h)

const container = document.getElementById('unit')
const shadowDOM = container.attachShadow({ mode: 'open' })

const keyframes = goober.keyframes.bind({ target: shadowDOM })
const styled = goober.styled.bind({ target: shadowDOM })

const Test = styled('div')(() => ({
  width: '200px',
  height: '200px',
  backgroundColor: 'red'
}))

render(<Test />, shadowDOM)
```

And it seems to work fine until I try to add keyframes

```
import { h, render } from 'preact'
import { setup } from 'goober'
import * as goober from 'goober'

setup(h)

const container = document.getElementById('unit')
const shadowDOM = container.attachShadow({ mode: 'open' })

const keyframes = goober.keyframes.bind({ target: shadowDOM })
const styled = goober.styled.bind({ target: shadowDOM })

const Animation = keyframes`
  from {
    height: 0px;
  }
  to {
    height: 200px;
  }
`

const Test = styled('div')(() => ({
  width: '200px',
  height: '200px',
  backgroundColor: 'red',
  animation: `${Animation} ease-in 3s`
}))

render(<Test />, shadowDOM)
```

Somewhy it doesn't account for a binded target and still render keyframes into head
![image](https://user-images.githubusercontent.com/59695738/121556120-46c2d200-ca1c-11eb-8c4c-0375b5ff3a30.png)

Which leads to keyframe animations not working

**Comment by cristianbote** [comment]
Hi @stepan-dashkevich!

Agh, this is a strange one. Let me look into it. Also keep in mind that `keyframes` is basically this:

```js
const keyframes = css.bind({ k: 1 });
```

So you might try this:

```js
const keyframes = css.bind({ k: 1, target: shadowDOM });
```

But it should work just fine as you had it initially, gonna look into it.

**Comment by stepan-dashkevich** [comment]
@cristianbote Tried this same code with what you've suggested and it worked for me. Thanks!

**Comment by cristianbote** [comment]
Awesome news @stepan-dashkevich! Going to close this then, let me know if this is still not working.
