### ISSUE TITLE
Cannot wrap the application to properly work with server-side rendering for Nextjs and error on type with styled-tools

### ISSUE THREAD

**Issue by mimiqkz** [cristianbote/goober#331]
I have been trying to find a way for wrap the application to use with Nextjs. I followed the example shows in here https://codesandbox.io/s/eager-cherry-57c9u?file=/pages/_document.js. 
However, it doesn't seem to work when you're doing it with typescript

Also I got this error upon trying to use styled with styled-tools.
`Property 'theme' is missing in type '{ children: Element; }' but required in type 'Omit<ClassAttributes<HTMLElement> & HTMLAttributes<HTMLElement> & DefaultTheme & { theme: ThemeWithPalette; tone?: number | undefined; }, never>'.`
![image](https://user-images.githubusercontent.com/19761446/122826536-cd0bcd80-d2d2-11eb-9382-5665ce97c85d.png)

**Comment by cristianbote** [comment]
Hi @mimiqkz thanks for opening this issue!

Are you able to share a codesandbox with the code that is failing? 🤔  the linked one is the example. Also, looks like you are defining types for `styled-tools` and `goober` to work together? Sharing those would be helpful as well.

**Comment by mimiqkz** [comment]
@cristianbote Yes, here is something https://codesandbox.io/s/brave-proskuriakova-i4ews?file=/pages/index.tsx

**Comment by dougg0k** [comment]
Hey @mimiqkz you can try improving the typing.

`goober.d.ts`
```
declare module "goober" {
	export interface DefaultTheme extends StyledFunction {
		palette: YourPaletteType;
	}
}
```
