### ISSUE TITLE
Props filter doesn't work with `as`

### ISSUE THREAD

**Issue by mikestopcontinues** [cristianbote/goober#332]
Here's a [reproduction](https://codesandbox.io/s/next-goober-forwardprops-8x4pn?file=/pages/index.tsx). Note the console error:

```
Warning: Invalid value for prop `as` on <a> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://reactjs.org/link/attribute-behavior 
    at a
    at Link
    at a (webpack-internal:///./node_modules/goober/dist/goober.modern.js:10:1940)
    at IndexPage
    at App (webpack-internal:///./node_modules/next/dist/pages/_app.js:75:5)
    at ErrorBoundary (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:26:47)
    at ReactDevOverlay (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:86:23)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:160:5)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:648:24)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:784:25)
```

How it works:
1. Setup `shouldForwardProps((prop) => prop !== 'as')`
2. Create a goober styled component. (e.g. Div)
3. Use the component, `as={FuncComponent}` (e.g. Link)

Error: `as` is still passed through. In this case, to an `a`.

I have tried other variations as well. For instance, I can explicitly filter `!prop.startsWith('$')`, and yet props like `$hello` still pass through to the `as` component. I checked the filter function logic, and it really is returning `false` for the bad props.

The strange thing here is that in the code, it really looks like it should be doing the right thing.

**Comment by cristianbote** [comment]
Wondering if this bit here https://github.com/cristianbote/goober/blob/master/src/styled.js#L54 is causing this 🤔  the comment says it well, that should not fwd for strings or built-in nodes.

**Comment by cristianbote** [comment]
Also, `shouldForwardProp` really needs to be moved per `styled` call 😬 . What do you think? This will be a breaking change, which would call for a major `3` version.

**Comment by mikestopcontinues** [comment]
Yikes! I actually read that line of code a few times before posting, and I think because the effect was so unintuitive to me, I just didn't see it. 😓

My own mental-blindness aside, I do think the right behavior is to always filter props as the user describes. I don't see a case where props used for styling would be passed to a string element, but not a functional component. `as` is a good example of this problem, because goober uses it. Even if the underlying component supported `as`, what's the likelihood the values would line up? Even still, I'd be okay if it wasn't filtered by default, as long as I could choose to filter it.

I do see what you mean about local `shouldForwardProps`, since it is kinda case-by-case. I would prefer if the global `shouldForwardProps` was left as a fallback or an additional filter. I'm perfectly happy to limit myself to `!prop.startsWith('$')` for styling across a repo to avoid the overhead of custom rules.

I think I saw you say in a different thread that you didn't like the `$` props convention, but I would argue it could go a long way to keeping the codebase clean. If you switched to `$as` and always filtered `$`-props, you'd have a very regular interface that paralleled the convention popping up in styled-components, etc. Plus, the $ is kinda peanut shaped. 😉

**Comment by mpkelly** [comment]
One thing I just noticed is that `shouldForwardProp` is not called when the `styled` component is wrapped in a HOC. 

```JavaScript
// shouldForwardProp is called
const Component  = styled("span")`...`;

<Component ignore-me="value" />

<span/>


// shouldForwardProp is not called
const Component  = withHOC(styled("span")`...`);

<Component ignore-me="value" />

<span ignore-me="value"/>

```

I didn't look at the source yet to see why. In both cases, goober is receiving the props though. I will open a separate issue if I can confirm it is a bug.

**Comment by cristianbote** [comment]
This got fixed not sure why it didn't autoclosed 🤷
