### ISSUE TITLE
return generated css not the hash

### ISSUE THREAD

**Issue by vospascal** [cristianbote/goober#337]
is it posible to just return the generated css from this so i can use it like that

```import { styled } from 'goober';
const Btn = styled('button')(
    (props) => `
  border-radius: ${props.size}px;
`
);```

**Comment by vospascal** [comment]
never mind got it working in svelte already with custom components

<script>
import {css} from 'goober';
import {get_current_component} from "svelte/internal";
const component = get_current_component();

const shadowSheet = css.bind({target: component.shadowRoot})
const generatedClassname = shadowSheet` background: firebrick;  color: #fff; `;

console.log(component.shadowRoot.styleSheets); // <--here now its attached to the shadowRoot

</script>
<div class="{generatedClassname}">
    im a brick colored div
</div>

**Comment by vospascal** [comment]
would still be nice to get the sting for the stylesheet so you can manualy inject it

**Comment by vospascal** [comment]
@cristianbote i added it my self 

```
import { compile } from './core/compile';
import {astish} from "./core/astish";
import {parse} from "./core/parse";

/**
 * css entry
 * @param {String|Object|Function} val
 * @param {String} tag
 */
export function raw(val, tag) {
    let ctx = this || {};
    let _val = val.call ? val(ctx.p) : val;

    const compiled = _val.unshift
        ? _val.raw
            ? // Tagged templates
            compile(_val, [].slice.call(arguments, 1), ctx.p)
            : // Regular arrays
            _val.reduce((o, i) => (i ? Object.assign(o, i.call ? i(ctx.p) : i) : o), {})
        : _val;
    let ast = typeof compiled == 'object' ? compiled : astish(compiled);

    return parse(ast,tag );

}
```
usage this way i can manualy append it to the shadow dom or head of the document.
```
raw(`color:red;`, ':host')
```

**Comment by cristianbote** [comment]
@vospascal awesome! Yeah, you can easily import each function and use it. I've seen folks build their own `styled` api with these functions as well. That's what makes goober great! 💪 

Let me know if there's other info you need, but seems you got it.
