### ISSUE TITLE
New type in `2.0.39` breaks createGlobalStyles funcs

### ISSUE THREAD

**Issue by mikestopcontinues** [cristianbote/goober#347]
[This line](https://github.com/cristianbote/goober/commit/60e75f046beda9f78ff9acc209e03552de806af0#diff-bb31806b34e7d09f9fc65fb3e422c8d5d3a74a08164d3a59b3ba965004681ed0R18) now says that `(props: Theme<DefaultTheme>)`, rather than `(props: {theme: Theme<DefaultTheme>})`.

**Comment by jlalmes** [comment]
Hi @mikestopcontinues `(props: Theme<DefaultTheme>)` is the correct type. Please see the `Theme` type implementation here: https://github.com/cristianbote/goober/blob/master/goober.d.ts#L10

**Comment by mikestopcontinues** [comment]
Thanks @jlalmes, my bad!
