### ISSUE TITLE
"as" prop break component restyle

### ISSUE THREAD

**Issue by marconucara** [cristianbote/goober#348]
If you restyle a component using `styled(OriginalComponent)` syntax and then you use this restyled component with the prop `as` goober do not render the class of `OriginalComponent`, so you loose the original style. If you remove `as` everything works fine.

Here is an example with both goober component and native component wrapper:

https://codesandbox.io/s/vanilla-forked-re536?file=/src/index.js

**Comment by cristianbote** [comment]
Hey, thanks for opening this issue. Do you thing is related to this one #220?

**Comment by marconucara** [comment]
I don't thinks so, because if you check the rendered dom in my example you will see an item without two classes when you use the `as` prop.
I also suggest you to merge the other bug solution anyway, because probably evryone prefer a library with 30b more an 1 bug less.

**Comment by cristianbote** [comment]
Hey! Just checked with #392 https://codesandbox.io/s/vanilla-forked-y0cuc?file=/src/index.js and it works now. Publishing soon!
