### ISSUE TITLE
Passing a styled component to "as" produces a fatal error

### ISSUE THREAD

**Issue by cwgw** [cristianbote/goober#349]
Hello!

I'm seeing a browser-crashing bug when passing a styled component to the `as` prop of another styled component.

The snippet below produces the behavior—a stalled-out tab that eventually displays Chrome's "Aww snap" screen and Firefox's "This page is slowing down Firefox" notification (an infinite loop?).

```jsx
import { styled } from "goober"

const StyledButton = styled('button')({
  border: '1px solid currentColor',
  padding: '8px 16px',
});

const StyledLink = styled('a')({
  color: 'blue',
  border: 'none',
  textDecoration: 'underline',
});

const MyComponent = () => {
  return (
    <div>
      <StyledButton as={StyledLink} href="#">Button Link</StyledButton>
    </div>
  );
}
```

Here's a [sandbox](https://codesandbox.io/s/priceless-bhabha-uudfq) that demonstrates the issue.

**Comment by cristianbote** [comment]
Heyo! Thank you so much for opening this. Something is not right indeed. Hopefully gonna have some time to look into it.
