### ISSUE TITLE
Question: Could this support props-based styles?

### ISSUE THREAD

**Issue by robertwbradford** [cristianbote/goober#37]
Thank you for the great library! We currently use styled-components and find ourselves needing styles based on props fairly often. (i.e., https://www.styled-components.com/docs/basics#passed-props)

Haven't looked into styled-components' internals, but would this be possible without too much bloat?

**Comment by cristianbote** [comment]
Hey @robertwbradford, thanks for opening this issue!

Yes. All that `goober` does is basically append the generated `className` to the passed in `props`, which in turn are just send to the `createEement`(pragma) method. So, whatever the host renderer supports, `goober` does as well.
Here's a codesandbox with the exact example from `styled-component` docs. https://codesandbox.io/s/1ylj8jy5xj

Let me know if this answers your question, if not please reopen it.

Once again, thank you!

**Comment by robertwbradford** [comment]
Super, thanks!
