### ISSUE TITLE
About Licensing

### ISSUE THREAD

**Issue by nariakiraHara** [cristianbote/goober#378]
It was pointed out to me that the license for using this OSS in the project is either MIT or ISC.
The LICENSE file says MIT, but the package.json says ISC, but which is the official license?

**Comment by cristianbote** [comment]
Hey @nariakiraHara thanks for opening this issue.

You are correct, the package.json says ISC and the repo specifies MIT. Now looking into what is the difference between them besides naming and I can see that the MIT one allows private usage but the ISC one does not. Is this something that concerns you?

**Comment by nariakiraHara** [comment]
@cristianbote Thanks for the reply.
What I want to know is which license I should use in compliance with.
I don't think it's both ISC and MIT, but I'm not sure.
Is there any problem to use it according to ISC?

**Comment by nariakiraHara** [comment]
Hi @cristianbote

I'm sorry to keep you busy.
I really need a fix to change the license from ISC to MIT for use in a project.
Please confirm.

[#380](https://github.com/cristianbote/goober/pull/380)

**Comment by cristianbote** [comment]
Hey @nariakiraHara sorry, got sidetracked. Merged your PR gonna push a new release.

**Comment by cristianbote** [comment]
published 2.0.42
