### ISSUE TITLE
The CSS function doesn't extract the css for SSR (gatsby-plugin-goober)

### ISSUE THREAD

**Issue by HenrikDK2** [cristianbote/goober#379]
^^

## Button styled with css function
![Button styled with css function](https://user-images.githubusercontent.com/30632653/138365531-40181e0d-9b31-403f-a3e8-93cc3b0ae545.gif)

## Button styled with styled function
![Button styled with styled function](https://user-images.githubusercontent.com/30632653/138365563-f3eeaf91-4a90-44aa-a1c3-d91dc52edb13.gif)

Any fix for this would be appreciated, sometimes i have to make a container when i can't extend a specific function. Being able to use the css function for SSR would be nice instead of indirectly changing styles from a container or via. global stylesheet :)

**Comment by cristianbote** [comment]
@HenrikDK2 if you still happen to have this issue, please feel free to reopen this. Thank you!
