### ISSUE TITLE
Add support for @import

### ISSUE THREAD

**Issue by brantem** [cristianbote/goober#38]
`@import url('https://fonts.googleapis.com/css?family=Roboto');` will translate into `{https://fonts.googleapis.com/css?family=Roboto');}`

**Comment by pmkroeker** [comment]
This should probably just get flattened like how `@keyframe` is.

**Comment by cristianbote** [comment]
Hey @brantem, thank you for submitting this issue. Indeed, it seems that the `@import` syntax is not picked up by the _parse_ regex. My bet is the lack of `:` between `@import` and `url()`.

**Comment by pmkroeker** [comment]
Could we check for `^@i` and just return the string if true? I don't think `@i` is used for anything else in CSS.

**Comment by cristianbote** [comment]
That would work, for sure, but I'm thinking of re-thinking the parser and shave some more bytes. I'll get back with more stuff.

**Comment by cristianbote** [comment]
Fixed in https://github.com/cristianbote/goober/commit/0c687bb53bfcff4b13bb2b06d08cb703f6a259f8
