### ISSUE TITLE
Using goober in react-native for a unified code base

### ISSUE THREAD

**Issue by alan-ws** [cristianbote/goober#383]
#292 

> Hey @mikestopcontinues!
> 
> Thanks for opening this issue with a valid question! smile
> 
> One thing that is certain is that you won't be suffering from performance degradation, neither on the server nor on the client. That is a certainty. You can peak at the benchmark folder to get a thorough look inside.
> 
> What you will be not getting with goober is the developer experience that the teams behind styled-components and emotion have thought of. With goober you can add a .displayName for each styled component but that's mostly it in terms of debugging. One important thing that allowed goober to be really small is that I've come-up with a regex parser to parse out the tagged templates, that is really small and powerful. styled-components and emotion both use the same parser, as in stylis. Which is as well such a great project! At some point I even ran the goober css parsers on top of stylis tests, to make sure I'm implementing the right thing, and they pass. There's one small bug inside the parser right now, which is this one #173.
> 
> I'm really obsessed about the size. I've cut corners, sacrifice APIs only to keep goober under 1kB. That's why I launched The Great Shave Off campaign as well.
> 
> So, to conclude this, I've used goober across everywhere and I've been enjoying it so much! That's why I created it. I've seen it used on large projects, or small. At some point I even replaces the react-native's StyleSheet with goober and everything worked great! smile
> 
> Hopefully this answered most of your questions about goober. Let me know if I can do a better job at answering it.

Hey @cristianbote - would you be able to show me how you used goober with react-native. I am looking to unify a codebase and would like to use goober only for both react and react-native. I'd likely fork goober and implement the approach if I need to, unless it can work without adding much of the goober codebase

**Comment by cristianbote** [comment]
Hey there @alan-ws!

The way I've used goober in the past was with next.js(with preact) and a shared component source. Then I went ahead an configured next.js to alias everything `react-native` to another package that would export similar `react-native` APIs.

```js
config.resolve.alias = Object.assign({}, config.resolve.alias, {
    'react-native$': 'cramped,
    react: 'preact/compat',
    'react-dom': 'preact/compat',
    'react-dom/unstable-native-dependencies': 'preact-responder-event-plugin',
});
```

That `cramped` package (which I just made it public https://github.com/cristianbote/cramped) aliases most of the APIs that I needed it. So, feel free to add to that the things that are missing.

Let me know if you still have issues or other questions.
