### ISSUE TITLE
Conditional style

### ISSUE THREAD

**Issue by Adam-Collier** [cristianbote/goober#384]
Hi guys, I was wondering if it is possible to handle conditional styles based on whether a prop exists or not? I've done it before in styled-components using the below:

```js
${(props) =>
  props.$padding &&
    css`
      padding-left: 1rem;
      padding-right: 1rem;
`}
```

so if the padding prop exists the css will be applied, if not it will be ignored. Hope you can help!

**Comment by cristianbote** [comment]
Hey @Adam-Collier thanks for opening this issue!

You sure can! In goober though you don't need the `css` tagged template.
```js
import { styled } from 'goober';

const Div = styled('div')`
  ${props =>
    props.padding && `
      padding-left: 1rem;
      padding-right: 1rem;
    `}
`
```

**Comment by Adam-Collier** [comment]
I tried that and it worked fine 👍 but I did come across an issue when trying to do something like:

```js
 ${(props) =>
    props.$direction === 'row' &&
    `
    > * + * {
        margin-left: calc(${props.$gap} * 1rem);

        @media (max-width: 767px) {
          margin-left: calc(${props.$gap} * 0.75rem);
        }
      }
  `}
```

Say the direction prop is set to "column", then it adds "false" to the styles, affecting the next style declaration. I would have thought it would have acted the same as what you suggested above but it seems like that's not that case, any idea why?
![image](https://user-images.githubusercontent.com/20065745/141269255-37749136-e0be-4f2a-a91d-8b8c94803ab8.png)

**Comment by cristianbote** [comment]
🤔 that's strange. I quickly tested this in here https://codesandbox.io/s/restless-surf-5d8j4?file=/src/App.js and seems to be working fine with or without defining the padding conditional. I think though I am missing some more context on this.

**Comment by Adam-Collier** [comment]
I've tweaked your sandbox here to replicate: https://codesandbox.io/s/cranky-shaw-t9d0m?file=/src/App.js 🙂 If you open the dev tools you should see the issue I mentioned. If you then switch the prop value to "bloo" you will see that that works as expected

**Comment by cristianbote** [comment]
Thank you @Adam-Collier your sandbox lead me to find the issue. Opened-up a PR to address this (with a test of course). Will publish a new release soon.

**Comment by cristianbote** [comment]
Published 2.0.43

**Comment by cristianbote** [comment]
Just updated with the new version https://codesandbox.io/s/sad-fog-nnqcb?file=/src/App.js and it seem to be working -- except that `blah` is not a valid padding value 😄

**Comment by Adam-Collier** [comment]
Perfect! Thats working great 👍 I appreciate you taking the time to sort this and so quickly too! Yeahhhh "blah" was probably not the best choice but it got the point across 😅
