### ISSUE TITLE
question: can we add a custom prefix to the className instead of 'go'?

### ISSUE THREAD

**Issue by sanjayjb** [cristianbote/goober#387]
I have a scenario where there might be conflicting class names generated by gooober hash, is there anyway I can use a custom className prefix like 'be' instead of 'go'?

**Comment by B-Teague** [comment]
The chance of a collision with the hash function should be very low.  On the small occasion it does happen, you can reorder the properties around in one of the styled components to generate a different hash value.

```javascript
css`
   color: blue;
   min-width: 100px;
`
```

change to

```javascript
css`
   min-width: 100px;
   color: blue;
`
```

**Comment by B-Teague** [comment]
@cristianbote Maybe picking different prime values would help reduce collision rates?
[https://www.planetmath.org/goodhashtableprimes](https://www.planetmath.org/goodhashtableprimes)
out = 97
factor = 769

This might reduce collision rates without impacting performance or bundle size

**Comment by Profesor08** [comment]
@B-Teague how about this scenario?

```
const ChildA = styled("div")``;

const ChildB = styled("div")``;

const Parent = styled("div")`
  &:hover {
    ${ChildA.className} {
      color: red;
    }

    ${ChildB.className} {
      color: blue;
    }
  }
`;

export const App = () => {
  return (
    <Parent>
      <ChildA>ChildA</ChildA>
      <ChildB>ChildB</ChildB>
    </Parent>
  );
};
```

**Comment by B-Teague** [comment]
@Profesor08 Hmmm, I see where this could be a bit buggy if two different styled elements have the exact same css resulting in the same class name.  The current workaround would be to add the different hover values to the children instead of the parent.  

https://codesandbox.io/s/react-goober-forked-ynd84?file=/src/index.js

```javascript
const ChildA = styled("div")`
  &:hover {
    color: red;
  }
`;

const ChildB = styled("div")`
  &:hover {
    color: blue;
  }
`;

const Parent = styled("div")``;

function App() {
  return (
    <Parent>
      <ChildA>ChildA</ChildA>
      <ChildB>ChildB</ChildB>
    </Parent>
  );
}
```

**Comment by B-Teague** [comment]
@sanjayjb Does this PR #400 fix your issue?  Can you recreate your problem here?
https://codesandbox.io/s/react-goober-forked-3vnqd

**Comment by cristianbote** [comment]
@sanjayjb at this moment no. goober does not support this.
