### ISSUE TITLE
Property 'as' does not exist on type 'IntrinsicAttributes & Omit<ClassAttributes<HTMLInputElement> & InputHTMLAttributes<HTMLInputElement> & { ...; } & { ...; }, "theme">'

### ISSUE THREAD

**Issue by meftunca** [cristianbote/goober#406]
Property 'as' does not exist on type 'IntrinsicAttributes & Omit<ClassAttributes<HTMLInputElement> & InputHTMLAttributes<HTMLInputElement> & { ...; } & { ...; }, "theme">'

**Comment by cristianbote** [comment]
Which version of goober throws this?
