### ISSUE TITLE
Next JS typescript error

### ISSUE THREAD

**Issue by kasperaamodt** [cristianbote/goober#422]
Hi,

In the [_document.tsx](https://github.com/kasperaamodt/aamodt/blob/ts/pages/_document.tsx) file in next js, I have the snippet from the next js goober example. When I installed TS in the project, I get a type error on this.props.css;

`Property 'css' does not exist on type 'Readonly<RenderPageResult & { styles?: ReactFragment | ReactElement<any, string | JSXElementConstructor<any>>[]; } & HtmlProps> & Readonly<...>'.`

**Comment by cristianbote** [comment]
Oh hmm wonder how can you tell nextjs what props are gonna be coming from `getInitialProps()` call 🤔  that should be the fixed really. The `css` prop doesn't exist on `this.props.css` on document. Not really a goober related type issue.

**Comment by cristianbote** [comment]
@kasperaamodt let me know if you still have issues with this. Closing meanwhile.

**Comment by kasperaamodt** [comment]
I found this solution: https://gist.github.com/kasperaamodt/5011c710074b63a800f605e822f1aa83
