### ISSUE TITLE
Update csstype peer dependency package

### ISSUE THREAD

**Issue by alexey-koren** [cristianbote/goober#433]
Hello

We started to use react-hot-toast library. And you are their [dependency](https://github.com/timolins/react-hot-toast/blob/main/package.json).

And you have a peer dependency [csstype](https://github.com/frenic/csstype/releases) v^2.6.2, which is published at 29 Jan 2019

It seems like you used it only in your goober.d.ts, and I checked their updates, they added TTime into Properties interface generic for animations support and etc.

So the upgrade might be not heavy

Maybe you can update it to the latest version?

Thank you!

**Comment by cristianbote** [comment]
Hi @alexey-koren I think so! Since this is a peer dep shouldn't be that much of a breaking change. Would you like to open up a PR for this? I would much appreciate it!

**Comment by alexey-koren** [comment]
> Hi @alexey-koren I think so! Since this is a peer dep shouldn't be that much of a breaking change. Would you like to open up a PR for this? I would much appreciate it!

Okay. Should I also update your devDep to old cssType?

**Comment by alexey-koren** [comment]
@cristianbote #434 I saw that you are using an old version of package-lock, so I'm not sure if I should update it.

**Comment by cristianbote** [comment]
> @cristianbote #434 I saw that you are using an old version of package-lock, so I'm not sure if I should update it.

> 
> Okay. Should I also update your old cssType devDep?

Yes to dev devDep but let me update the package-lock since that's gonna be committed in here. How does that sound?

**Comment by alexey-koren** [comment]
> > @cristianbote #434 I saw that you are using an old version of package-lock, so I'm not sure if I should update it.
> 
> > Okay. Should I also update your old cssType devDep?
> 
> Yes to dev devDep but let me update the package-lock since that's gonna be committed in here. How does that sound?

Okay, done
