### ISSUE TITLE
[Help wanted] Gatsby Plugin

### ISSUE THREAD

**Issue by totsteps** [cristianbote/goober#44]
Thanks for the great library ♥️. I am trying to create a `gatsby-plugin-goober` but couldn't get the tests passing.

I am not really good with the tests 😬.

Repo: https://github.com/gagan0723/gatsby-plugin-goober

**Comment by cristianbote** [comment]
Awesome job @gagan0723! 🎉Really love how the community is contributing to this little library.
I'm gonna open a PR to your repo, in a few, with the tests fixes and some improvements.

I'm thinking to create a `packages` folder where we could keep all these packages. If you're open to it, we could move this under that. Either way, it's _your_ contribution 😃therefore you decide.

We'll do the next.js and preact-cli templates as well, and place them under `packages` as well.

Once again, great job!

**Comment by cristianbote** [comment]
Here's the PR https://github.com/gagan0723/gatsby-plugin-goober/pull/1

**Comment by gagan0723** [comment]
Thanks for the PR. Yeah, we can move `gatsby-plugin-goober` under `packages` 😀.

Closing this for now.

**Comment by gagan0723** [comment]
I want to keep this opened until we done moving `gatsby-plugin-goober` under `packages`.
Copying over the whole folder should do the job.

**Comment by cristianbote** [comment]
On it! 😄Will create the packages folder and we can go from there

**Comment by gagan0723** [comment]
@cristianbote any updates on this? Thanks

**Comment by cristianbote** [comment]
@totsteps finally managed to get it done! Kinda late but better late than never, I guess.
Here's the pr #81
