### ISSUE TITLE
A newline will cause meaningful whitespace to be stripped.

### ISSUE THREAD

**Issue by jackmoore** [cristianbote/goober#447]
This:
```
css`
background: #000
	no-repeat;
`
```
Gets outputted as this:
```
#000no-repeat
```

Same thing if it's spaces instead of tabs. If a newline is in the mix, the space/tab gets stripped also. Our project's code-formatting tool is inserting line-breaks creating invalid CSS when run through Goober v2.1.8.

**Comment by cristianbote** [comment]
Hey @jackmoore, thanks for opening this issue.

Indeed 😞 I believe the space and comment cleanup regex rule replaces them with nothing. I believe replacing those with a space instead would make the syntax valid again.

**Comment by cristianbote** [comment]
Published `v2.1.9` with the fix for the above.
