### ISSUE TITLE
How does this library achieve such a small size?

### ISSUE THREAD

**Issue by vedantroy** [cristianbote/goober#454]
This library is over 10x smaller than similar libraries, which is super impressive!
I was wondering what the trade-off is. I.e., presumably there is a reason other libraries are 10x the size.
And I assume the people behind styled-components & emotion are also trying hard to optimize their bundle sizes.
So what gives?

**Comment by cristianbote** [comment]
Hey @vedantroy, thanks for opening this issue.

Indeed, there are definitely some tradeoffs. I created this feature tradeoffs list in here https://github.com/cristianbote/goober#comparison-and-tradeoffs specifically to address some of the concerns and valid questions.
* goober has it's own css parser which I believe styled-components and emotion are using stylis lib. 
* styled-components and emotion manage their own styling rules by architecting a system to manage the stylesheet, whereas goober relies on the actual `style` tag contents as that system.
* developer utilities and helpers are not present in goober, such as `styled.<tagName>`.

I believe that's mostly it.
