### ISSUE TITLE
feature request: publish to deno module?

### ISSUE THREAD

**Issue by parkjh** [cristianbote/goober#464]
Hi,

I was just wondering if this repository could be setup to publish to [deno](https://deno.land/x)?
I ask because the instruction shown requires access to [webhooks settings](https://deno.land/add_module), but it seems quite straightforward.

**Comment by cristianbote** [comment]
Hey @parkjh,

Thanks for opening this issue! Managed to published it there as well https://deno.land/x/goober 🙌
