### ISSUE TITLE
Typescript theme types not working as expected

### ISSUE THREAD

**Issue by mtmeyer** [cristianbote/goober#489]
Not sure if this is to do with how I've set goober up but I'm having an issue where Typescript doesn't seem to be working properly when referencing theme props in the `styled` function.  In the example below TS says "Property theme does not exist on type etc..." but in practice this works perfectly.
```typescript
const TestComponent = styled('div')`
    background-color: ${(props) => props.theme.color.primary};
`
```

I've created a `goober.d.t.s` file as per the documentation.  Am I missing something here?

**Comment by mtmeyer** [comment]
Nevermind, turns out i just had to move the `goober.d.ts` file into the src directory.  Wondering if it's worth updating the documentation to reflect this?  Also the documentation explicitly states `goober.d.t.s` and I'm not sure if this is a typo or not. https://goober.js.org/features/typescript#extending-theme

**Comment by cristianbote** [comment]
Hey @mtmeyer, this is definitely a typo in the docs 😓
