### ISSUE TITLE
Option for className or class?

### ISSUE THREAD

**Issue by fabiancook** [cristianbote/goober#51]
https://github.com/cristianbote/goober/blob/831917013b16141d08feb1b88a304da5ee69269f/src/styled.js#L21

It would be great if we could utilise `class` instead of `className`

I utilize `class` as I'm writing direct one to one with static html

**Comment by fabiancook** [comment]
This could work the same as `setPragma` 

`setClassNameProperty(property: string)`

It wouldn't work nice for types though, I think if you were to support typescript types completely you would need to have both the pragma and class name as direct options to `styled`

**Comment by cristianbote** [comment]
Hey @fabiancook thanks for opening this issue!

Using `class` vs `className` is actually quite different in terms of code path. `class` is an attribute and `className` is a property. Setting `class` uses `.setProperty` and `className` is basically a getter/setter that handles the DOM updates internally. Take a look over this bench https://esbench.com/bench/5d9464444cd7e6009ef62801.

I had a quick check over the other `css-in-js` implementations and neither of them seem to use `class`.

Though there is a way you could achieve this, if you're really settled on using `class`, by using the `css` function.

```jsx
import { css } from "goober";

const cls = css`
  background: tomato;
`;

// ...later on
function Button() {
  return <button class={cls}>clicky</button>
}
```

Let me know what you think

**Comment by fabiancook** [comment]
> Though there is a way you could achieve this, if you're really settled on using class, by using the css function.
Perfect that's what I was looking for then, works in all scenarios, I could then wrap that same function with whatever I wanted, so that works as well. 

Thank you!

**Comment by fabiancook** [comment]
As a reference as well, because I'm targeting only static html, the difference of `setAttribute` and setting the property doesn't change too much for me

**Comment by cristianbote** [comment]
I'm glad you can use the `css`. Fun fact, `styled` uses the same `css` internally 😄 and just returns the `className`.
