### ISSUE TITLE
Type definitions for styled() functions

### ISSUE THREAD

**Issue by mjanssen** [cristianbote/goober#52]
When using typescript with styled component libraries, you can pass the type of the props to the styled Component, to enforce correct property names and having autocompletion for the props object.

**Example**
```
type ParagaphType = {
  style?: object;
  color?: string;
};

const P = styled('div')<ParagaphType>`
  color: ${props => (props.color ? props.color : 'black')};
  margin: 0;
  padding: 0;
  ${props => props.style && { ...props.style }}
`;
```

With Goober, I'm getting the following typescript problem when implementing the same syntax.

![image](https://user-images.githubusercontent.com/1145427/66042870-f6dcf980-e51d-11e9-9175-56035ee3d632.png)

Could we update the type defs for Goober to have the autocompletion as well?

**Comment by cristianbote** [comment]
Summoning @pmkroeker 😄 What do you think? Is that doable?

Peter wrote the entire type definitions so he's the most capable one to answer that question.

**Comment by pmkroeker** [comment]
Ya that should be pretty straightforward. I can take a look quick. Pretty busy with work right now, but it should be a pretty simple fix.
