### ISSUE TITLE
@font-face escaping

### ISSUE THREAD

**Issue by realignedTech** [cristianbote/goober#54]
There seems to be an issue with the @font-face notation. When supplied via glob() it gets double { } so this

` @font-face {
    font-family: "Source Sans Pro";
    font-style: normal;
    font-weight: 400;
    src: local("Source Sans Pro Regular"), local("SourceSansPro-Regular"),
      url(${woff2}) format("woff2"),
      url(${woff1}) format("woff");
  }` translates to 

`@font-face{{font-family:"Source Sans Pro";font-style:normal;font-weight:400;src:local("Source Sans Pro Regular"), local("SourceSansPro-Regular"),url(/c85615b296302af51e683eecb5e371d4.woff2) format("woff2"),url(/a75563d7b9e5b1db163971b9a2e66216.woff) format("woff");}}`

Removing the double { resolved the issue and the browser loads the webfonts

**Comment by cristianbote** [comment]
Thank you! 😀 that was indeed a strange one. I'm gonna do the release soon.
