### ISSUE TITLE
(chore) switch to a monorepo to include the templates as well

### ISSUE THREAD

**Issue by cristianbote** [cristianbote/goober#56]
It'll be helpful to have a `lerna` monorepo, so we could have the same related packages inside one main repo.

**Comment by Hotell** [comment]
btw yarn workspaces are all you might need. but ofc YMMV 🌻

**Comment by cristianbote** [comment]
Yeah, `worksapaces` would definitely work, just fine, I only like `lerna` because of the out-of-the-box no hoisting 😄 so it doesn't get in your way.

I should add the packages though. That way it's gonna be easier to add the missing puzzle pieces.
