### ISSUE TITLE
Incomplete TypeScript definitions - 'goober' has no exported member 'glob'

### ISSUE THREAD

**Issue by kolodziejczakM** [cristianbote/goober#57]
![obraz](https://user-images.githubusercontent.com/16230707/69357756-f4795f00-0c85-11ea-8428-feda001ff06c.png)
![obraz](https://user-images.githubusercontent.com/16230707/69357809-0bb84c80-0c86-11ea-9f65-3dabacf0f338.png)

**Comment by cristianbote** [comment]
Hey @kolodziejczakM, thanks for opening this and taking the time to look into it! Indeed that seems to be missing. Do you wanna open a PR for it? That would mean a lot for me.

Have a great one, cheers!

**Comment by kolodziejczakM** [comment]
Oh you're faster than me 👍

**Comment by cristianbote** [comment]
Oh, sorry about that. I thought I should fix it, since I was adding some tests. Feel free to grab any other issue or improvement 😉 it's wide open.
