### ISSUE TITLE
How to use with postcss?

### ISSUE THREAD

**Issue by mg901** [cristianbote/goober#59]
Hi, thank you for you awesome tool? Is it possible to share with postcss plugins?

**Comment by cristianbote** [comment]
Hey @mg901 thanks for reaching out! :)
That's a pickle! I haven't used it before with postcss. What would this entail? Or more exactly what's the exact setup where yo have postcss running along with goober? If there's a repo you could share or an example, that would be even more helpful to debug.

**Comment by cristianbote** [comment]
Haven't heard from the opener in a while. I'm gonna close this. If there are more questions feel free to post them in here.

**Comment by vvni** [comment]
In fact, this function is pretty good.
