### ISSUE TITLE
Theming solution?

### ISSUE THREAD

**Issue by nygdjs** [cristianbote/goober#61]
Thanks for this absolute awesomeness! I'm super excited, as on one of my projects we are currently try to find powerful, yet very lightweight solutions, and goober seems to fit in perfectly.
However I use styled-components on other projects for many reasons, but one of them surely is the powerful theming built-in. 
Do you plan something similar, or have any idea how to do something like that?

**Comment by cristianbote** [comment]
Hey @nygdjs, thank you so much for your kind words! Really appreciate it!

So, theming is something that would increase the size of the bundle and would require `goober` to be specifically integrate with your framework. That means, `web-componens` could not make use of goober and `preact` for example would need to include the `preact/compat` layer to handle the theming part -- since that would rely on context api.

Do you see yourself in need of such api? Maybe I'm not seeing it, yet, what would theming help with. Could you give me an example?

Thank you so much for opening this!

**Comment by donysukardi** [comment]
This seems doable if `gobber` provides a settable additional props getter/hook.

In gobber,

```jsx
let useAdditionalProps = () => ({})
const setUseAdditionalProps = fn => { useAdditionalProps = fn }

// in styled fn add the following
const additionalProps = useAdditionalProps();
const _props = Object.assign({}, props, additionalProps);
```

In user code,

```jsx
setUseAdditionalProps(() => {
  const theme = React.useContext(ThemeContext);
  return { theme }
})

// now props.theme is available to the styled components
```

**Comment by Hotell** [comment]
> and preact for example would need to include the preact/compat layer to handle the theming part -- since that would rely on context api.

I had impression that context api is build in within Preact X no ? https://preactjs.com/guide/v10/context

**Comment by Hotell** [comment]
I suggest to have theming provider as separate package to not increase lib size etc -> also it's always cleaner approach to have plugins 👌

**Comment by cristianbote** [comment]
@Hotell yup, preact has the context api in core, but integrating the context api as imported from `React`, would mean other libs would have to add their compat layers to mock `React`.

**Comment by donysukardi** [comment]
With my proposal above, the integration with context api is done on userland (via hook) so the library is still agnostic

**Comment by cristianbote** [comment]
Just looked over, a second time. You are right 👍💯Do you wanna open a PR? 😄
Also, how about we merge the `setPragma` and `setTheme`? Hopefully we could save some more bytes

**Comment by donysukardi** [comment]
What do you think of having a `setup({ pragma, forwardRef, useTheme })` function instead?

**Comment by cristianbote** [comment]
This is now part of `@2.x.x` release. If there are more questions feel free to post them in here. I'm gonna close this now.
