### ISSUE TITLE
(feat) Add/create a babel plugin for `styled.<tagName>`

### ISSUE THREAD

**Issue by cristianbote** [cristianbote/goober#69]
As @jviide built this https://github.com/jviide/babel-plugin-transform-styledodo we could leverage it and create a babel plugin, to help people used with the `styled.div` pattern.

**Comment by JoviDeCroock** [comment]
I don't mind looking into this in the near future, the goal of this would be to achieve syntactical parity to `styled-components or @emotion/styled`?

**Comment by cristianbote** [comment]
Thank you @JoviDeCroock! :) So happy to have you here!

Do you know if there _are_ differences between them?

**Comment by jviide** [comment]
Had a chat with @JoviDeCroock, who encouraged me to finally collect the stuff from https://github.com/jviide/babel-plugin-transform-styledodo and create PR #86.

**Comment by cristianbote** [comment]
Merged in #86
