### ISSUE TITLE
Where to discuss about and direction of goober? Should we keep gitter, slack or ...?

### ISSUE THREAD

**Issue by cristianbote** [cristianbote/goober#73]
Currently goober has the gitter chat room to be able to chat and discuss. Recently I've setup a slack workspace as well. But I'm wondering what would be the best option?  I'm currently online constantly on slack so I'm really inclined to move the discussion in there.

Would you as part of the community, use slack to get in touch and talk about goober?

Looking forward to your feedback! ✌️

Edit: Here's the slack space invite link https://join.slack.com/t/gooberdev/shared_invite/enQtOTM5NjUyOTcwNzI1LWUwNzg0NTQwODY1NDJmMzQ2NzdlODI4YTM3NWUwYjlkY2ZkNGVmMTFlNGMwZGUyOWQyZmI4OTYwYmRiMzE0NGQ

**Comment by manuschillerdev** [comment]
Where can I find the slack channel? Would love to join :)

**Comment by cristianbote** [comment]
Heyo! It's `gooberdev` as a space name. 😄 It's just me in there for now!

**Comment by cristianbote** [comment]
Alrighty, `slack` it is :)
