### ISSUE TITLE
Trim a few bytes, but mutate arguments

### ISSUE THREAD

**Issue by pronevich** [cristianbote/goober#75]
Goober trying be as small as possible. Does it make sense to trim bytes by using `shift` instead `slice` by mutating arguments in `css()`?

```js
function css() {
    const val = arguments.shift();
    const ctx = this || {};
    const _val = val.call ? val(ctx.p) : val;

    return hash(
        _val.map ? compile(_val, arguments, ctx.p) : _val,
        getSheet(ctx.target),
        ctx.g,
        ctx.o
    );
}
```

1017B > 1014B

**Comment by cristianbote** [comment]
Hey @pronevich thank you for opening this! Really appreciate it!

This looks really good! 🙂 Really like it! Would you like to open a PR?

**Comment by pronevich** [comment]
Sure)

**Comment by pronevich** [comment]
I just realized that this code won't pass tests: ` TypeError: arguments.shift is not a function`. What is quite understandable.

**Comment by cristianbote** [comment]
Ah, yeah indeed. In any case that was a nice proposal! 😃 thank you for your time!
