### ISSUE TITLE
Goober fork published on npm!!

### ISSUE THREAD

**Issue by totsteps** [cristianbote/goober#82]
I found this guy with the name **Nikhil Saraf** who published goober fork under his name as [@nksaraf/goober](https://www.npmjs.com/package/@nksaraf/goober) on npm!!
 
Github https://github.com/nksaraf

@cristianbote

**Comment by cristianbote** [comment]
Hey @totsteps, thanks for pointing it out. No worries here. I think he did that so he could explore integrating it with his work -- seeing that `@nksaraf/goober` it's used by `preact-box` and `@react-box/preact`.

Keep up the good work! 😉
