### ISSUE TITLE
css(taggedTemplate) styntax is returning a string instead of a function

### ISSUE THREAD

**Issue by raulgg** [cristianbote/goober#89]
I was following the documentation for the css syntax and trying to test it on my project I found that css is returning a string with the classname hash instead of returning a function as showed in the docs.

https://github.com/cristianbote/goober/blob/master/README.md#csstaggedtemplate

I took a look into the source code and it seems that returning the hash instead of the function seems intentional. So I'm guessing that this is matter of updating the docs? Or am I missing something?

**Comment by cristianbote** [comment]
Hey @raulgg! Thanks for opening this issue.

Yeah it's a documentation error 😅 would you like to open a PR to fix it? I would really appreciate it.

**Comment by raulgg** [comment]
Sure, I'll take some time to update the docs over the next two days.

**Comment by cristianbote** [comment]
Closed via @raulgg PR. Thanks a bunch!
