### ISSUE TITLE
Any solution for specificity for `css`

### ISSUE THREAD

**Issue by ryansolid** [cristianbote/goober#98]
I've been testing Goober with my library Solid (https://github.com/ryansolid/solid). It uses JSX but no VDOM, but rather a reactive system. It doesn't compile JSX to HyperScript variant so using the built-in Styled in this library isn't applicable. However, the css helper is easy to wrap into `styled` variant.

One thing I noticed was that `styled` in this library seems to just concat classNames as it compounds styled but that doesn't work for specificity, because the order you generally execute Components the first time it is opposite. For example:

```jsx
const Div = styled("div")`
  color: red;
  font-size: 32px;
  padding: 5px;
  border: 2px solid black;
  background-color: purple;
`;

const StyledDiv = styled(Div)`
  background-color: lightblue;
  font-weight: ${props => (props.bold ? "bold" : 100)};
`;
```
`StyledDiv` ends up purple since it gets created before `Div`. and when bold is toggled it switches to lightblue as the new class is created after.

Emotion uses a helper (`cx`) both to concat names but more importantly detect classes it has generated and merge them to ensure the right overrides occur. I was wondering if Goober had or was intending to have an equivalent?

**Comment by cristianbote** [comment]
Hey @ryansolid,

Thanks for opening this question and trying goober for solid! 😄 

So, `styled` does have the specificity awareness based on previous classes being present which would dictate the append or prepend method. It's in here: https://github.com/cristianbote/goober/blob/master/src/styled.js#L20.

If you want to mimic the `styled` with `css` that would mean you'd have to wrap css and pass that flag depending on your logic. `_ctx.o` is that flag. So if that's true the stylesheet it's either prepended or appended, called in here: https://github.com/cristianbote/goober/blob/master/src/core/hash.js#L19.

Also looked at the linked emotion codesandbox and took a stab at it 😄 https://codesandbox.io/s/solid-goober-poxg5 if `css` it's called with the `o: true` flag properly everything should be working fine.

If you have other questions/improvements, do let me know 😃!

Thanks again for looking into it!

**Comment by ryansolid** [comment]
Awesome. This is what I was looking for. I missed that piece around the `_ctx` object. It simplifies things greatly. Thanks for taking the time to make a working example.

With that knowledge I'm going to see what other applications using `css` there are. Since all the core functionality is there and the `styled` approach is a minor deoptimization in Solid as it breaks apart templates. Solid's compiler dealing with real DOM nodes clones the continuous templates. So wrapping a bunch of elements independently does no favours.

I will let you know if I come across anything else or have any ideas. Thanks again.

**Comment by Ashkar2023** [comment]
when using `styled` fn is there any way to append the className?

I am using react & testing out goober and tailwind for an npm package.
https://npmjs.org/package/breakpointer

**Comment by cristianbote** [comment]
heya @Ashkar2023 you can use the `className` prop on the component itself, just like a regular component. Have you tried that or running into issues?

**Comment by Ashkar2023** [comment]
I have tried giving values to className, but the CSS set at styled is not overridden unless the `!important` specifier is given

```
import { FC, HTMLAttributes, useMemo, useState } from "react";
import { useBreakpointer } from "../hooks/useBreakpointer";
import { styled } from "goober";
import { Laptop, LucideIcon, Monitor, Smartphone, Tablet, TabletSmartphone, Tv } from "lucide-react";
import { breakpointsConstants } from "../core/constants/breakpoints";


const Wrapper = styled("div") <{ position: "left" | "right" }>`
    display: grid;
    grid-template-columns: 1fr 1fr;
    grid-template-rows: auto auto;
    background-color: rgb(15, 15, 15);
    border-radius: 5%;
    min-width: 60px;
    color: white;
    position: fixed;
    bottom: 30px;
    min-height: 60px;
    z-index: 10000;
    ${({ position }) => position === "right" ? "right: 30px;" : "left: 30px;"}
`;

const Col1 = styled("div")`
    align-content: center;
    justify-items: center;
    padding-inline: 3px;
    &:nth-child(odd){
        align-content: center;
        border-right: 1px solid gray;
    }

`;

const Col2 = styled("div")`
    border-top: 1px solid gray;
    grid-column: 1/3;    
    align-content: center;
    justify-items: center;
`;


const breakpointIcons: {
    [key in keyof typeof breakpointsConstants | string]: LucideIcon
} = {
    "sm": TabletSmartphone,
    "md": Tablet,
    "lg": Laptop,
    "xl": Monitor,
    "2xl": Tv,
}

type InternalElements = "wrapper" | "iconWrapper" | "screen" | "currentWidth";

export interface BreakpointerIndicatorProps extends HTMLAttributes<HTMLDivElement> {
    classNames?: Partial<Record<InternalElements, string[]>>
};

export const BreakpointerIndicator: FC<BreakpointerIndicatorProps> = ({ className, ...props }) => {
    const { currentWidth, screen } = useBreakpointer();

    const [right, setRight] = useState(false);

    const Icon: LucideIcon = useMemo(() => {
        if (screen in breakpointsConstants) {
            return breakpointIcons[screen]
        } else {
            return Smartphone;
        }
    }, [screen]);

    return (
        <Wrapper
            position={right ? "right" : "left"}
            onMouseEnter={() => {
                setRight(prev => !prev)
            }}
            className={[className, props.classNames?.wrapper?.join(" ")].join(" ")}
        >
            <Col1 className={props.classNames?.iconWrapper?.join(" ")}>
                <Icon size={20} />
            </Col1>
            <Col1 className={props.classNames?.screen?.join(" ")}>
                <b
                    style={{
                        textOverflow: "ellipsis",
                        overflow: "hidden",
                        whiteSpace: "nowrap",
                    }}
                >{screen}</b>
            </Col1>
            <Col2 className={props.classNames?.currentWidth?.join(" ")}>
                <p style={{ margin: 0 }}>{currentWidth}<small>px</small></p>
            </Col2>

        </Wrapper >
    )
}
```

usage of the component
```
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import "./index.css"
import App from './App.tsx'
import { BreakpointerProvider } from "breakpointer"

import resolveConfig from "tailwindcss/resolveConfig"
import tailwindConfig from "../tailwind.config"


createRoot(document.getElementById('root')!).render(
    <StrictMode>
        <BreakpointerProvider
            mode={import.meta.env.MODE}
            breakpointsObj={resolveConfig(tailwindConfig).theme.screens}
            classNames={{
                iconWrapper:["!content-end"] // this works, but without ! specifier it won't.
            }}
        >
            <App />
        </BreakpointerProvider>
    </StrictMode>,
)

```
